import { TechCategory } from "@/types";

export const categories: TechCategory[] = [
  {
    id: "frontend",
    name: "Frontend",
    description: "Modern frameworks and libraries for building responsive and interactive user interfaces.",
    icon: "Code2",
    displayOrder: 1,
    gradient: "from-blue-500 to-indigo-500",
  },
  {
    id: "backend",
    name: "Backend",
    description: "Robust and secure server-side technologies powering application logic and processing workflows.",
    icon: "Server",
    displayOrder: 2,
    gradient: "from-green-500 to-emerald-500",
  },
  {
    id: "database",
    name: "Database",
    description: "Reliable data stores, caching layers, and search index providers that store and retrieve structured data.",
    icon: "Database",
    displayOrder: 3,
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "cloud",
    name: "Cloud",
    description: "Cloud-native databases, serverless platforms, and backend-as-a-service providers.",
    icon: "Cloud",
    displayOrder: 4,
    gradient: "from-sky-500 to-blue-500",
  },
  {
    id: "devops",
    name: "DevOps",
    description: "Infrastructure management, containerization, deployments, and continuous delivery.",
    icon: "Wrench",
    displayOrder: 5,
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "authentication",
    name: "Authentication",
    description: "Identity management, security protocols, roles, and granular authorization controls.",
    icon: "Lock",
    displayOrder: 6,
    gradient: "from-red-500 to-rose-500",
  },
  {
    id: "architecture",
    name: "Architecture",
    description: "Architectural standards, APIs, microservices structure, design patterns, and scaling protocols.",
    icon: "Layers",
    displayOrder: 7,
    gradient: "from-slate-500 to-slate-700",
  },
  {
    id: "search",
    name: "Search",
    description: "Fast indexing, typographic matching, and instant searching technologies.",
    icon: "Search",
    displayOrder: 8,
    gradient: "from-cyan-500 to-teal-500",
  },
  {
    id: "integrations",
    name: "Integrations",
    description: "Automations, payment gateways, and data processing pipeline integrations.",
    icon: "Plug",
    displayOrder: 9,
    gradient: "from-indigo-500 to-violet-500",
  },
  {
    id: "tools",
    name: "Tools",
    description: "Core developer utilities, environment workspaces, and control structures.",
    icon: "Wrench",
    displayOrder: 10,
    gradient: "from-zinc-500 to-zinc-700",
  },
  {
    id: "ui-libraries",
    name: "UI Libraries",
    description: "Aesthetic interfaces, animation engines, and components for rapid styling layout creation.",
    icon: "Palette",
    displayOrder: 11,
    gradient: "from-fuchsia-500 to-purple-500",
  },
];
