import { TechCategory } from "@/types";

export const categories: TechCategory[] = [
  {
    id: "frontend",
    name: "Frontend",
    description: "UI frameworks, browser technologies and design systems.",
    icon: "Code2",
    displayOrder: 1,
    gradient: "from-cyan-500 to-blue-600",
  },
  {
    id: "backend",
    name: "Backend",
    description: "Server-side languages, frameworks, APIs and patterns.",
    icon: "Server",
    displayOrder: 2,
    gradient: "from-purple-500 to-indigo-600",
  },
  {
    id: "mobile",
    name: "Mobile",
    description: "Cross-platform and native mobile development.",
    icon: "Smartphone",
    displayOrder: 3,
    gradient: "from-green-500 to-emerald-600",
  },
  {
    id: "database",
    name: "Database",
    description: "Relational, NoSQL, caching and database practices.",
    icon: "Database",
    displayOrder: 4,
    gradient: "from-orange-500 to-amber-600",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    description: "Containerization, web servers, OS and hosting tools.",
    icon: "Server",
    displayOrder: 5,
    gradient: "from-slate-500 to-zinc-600",
  },
  {
    id: "deployment",
    name: "Deployment & CI/CD",
    description: "Cloud platforms, pipelines and release workflows.",
    icon: "Rocket",
    displayOrder: 6,
    gradient: "from-violet-500 to-purple-600",
  },
  {
    id: "ai",
    name: "AI & Automation",
    description: "AI APIs, LLM integration and intelligent automation.",
    icon: "Sparkles",
    displayOrder: 7,
    gradient: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "dev-tools",
    name: "Developer Tools",
    description: "Editors, package managers, linters and productivity tools.",
    icon: "Wrench",
    displayOrder: 8,
    gradient: "from-yellow-500 to-orange-600",
  },
  {
    id: "security",
    name: "Security",
    description: "Authentication, authorization and security practices.",
    icon: "Shield",
    displayOrder: 9,
    gradient: "from-red-600 to-orange-600",
  },
  {
    id: "laravel-ecosystem",
    name: "Laravel Ecosystem",
    description: "Laravel-specific features, tools and conventions.",
    icon: "Package",
    displayOrder: 10,
    gradient: "from-red-500 to-orange-500",
  },
  {
    id: "e-commerce",
    name: "E-commerce",
    description: "Product, order, inventory and payment management.",
    icon: "ShoppingCart",
    displayOrder: 11,
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: "payments",
    name: "Payments",
    description: "Payment gateways, webhooks and financial integrations.",
    icon: "CreditCard",
    displayOrder: 12,
    gradient: "from-blue-800 to-indigo-800",
  },
  {
    id: "storage",
    name: "File Storage",
    description: "File upload pipelines and storage management.",
    icon: "Upload",
    displayOrder: 13,
    gradient: "from-blue-500 to-indigo-600",
  },
  {
    id: "engineering-practices",
    name: "Engineering Practices",
    description: "Architecture, patterns, testing, debugging and optimization.",
    icon: "ShieldCheck",
    displayOrder: 14,
    gradient: "from-slate-600 to-gray-700",
  },
  {
    id: "git-workflow",
    name: "Git Workflow",
    description: "Version control, branching strategies and collaboration.",
    icon: "GitBranch",
    displayOrder: 15,
    gradient: "from-orange-600 to-red-600",
  },
  {
    id: "business",
    name: "Business & Agency",
    description: "Proposals, discovery, planning and client management.",
    icon: "Briefcase",
    displayOrder: 16,
    gradient: "from-teal-500 to-cyan-600",
  },
];
