import { TechCategory } from "@/types";

export const categories: TechCategory[] = [
  {
    id: "frontend",
    name: "Frontend",
    description: "Modern frameworks and libraries for building responsive and interactive user interfaces.",
    icon: "Code2",
    displayOrder: 1,
    gradient: "from-blue-500 to-indigo-500",
  },
  {
    id: "backend",
    name: "Backend",
    description: "Robust and secure server-side technologies powering application logic and processing workflows.",
    icon: "Server",
    displayOrder: 2,
    gradient: "from-green-500 to-emerald-500",
  },
  {
    id: "mobile",
    name: "Mobile",
    description: "Cross-platform and native mobile development frameworks.",
    icon: "Smartphone",
    displayOrder: 3,
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "database",
    name: "Database",
    description: "Reliable data stores, caching layers, and search index providers.",
    icon: "Database",
    displayOrder: 4,
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    description: "Containerization, virtualization, and infrastructure management tools.",
    icon: "Layers",
    displayOrder: 5,
    gradient: "from-sky-500 to-cyan-500",
  },
  {
    id: "deployment",
    name: "Deployment",
    description: "Hosting, CI/CD, and environment management tools.",
    icon: "Rocket",
    displayOrder: 6,
    gradient: "from-indigo-500 to-violet-500",
  },
  {
    id: "ai",
    name: "AI",
    description: "Artificial intelligence and machine learning tools and APIs.",
    icon: "Sparkles",
    displayOrder: 7,
    gradient: "from-fuchsia-500 to-rose-500",
  },
  {
    id: "development-tools",
    name: "Development Tools",
    description: "Core developer utilities, version control, and debugging tools.",
    icon: "Wrench",
    displayOrder: 8,
    gradient: "from-zinc-500 to-zinc-700",
  },
  {
    id: "search",
    name: "Search",
    description: "Search and indexing technologies.",
    icon: "Search",
    displayOrder: 9,
    gradient: "from-cyan-500 to-teal-500",
  },
  {
    id: "storage",
    name: "Storage",
    description: "File storage and upload pipeline solutions.",
    icon: "UploadCloud",
    displayOrder: 10,
    gradient: "from-emerald-500 to-green-500",
  },
  {
    id: "payments",
    name: "Payments",
    description: "Payment gateway integrations.",
    icon: "CreditCard",
    displayOrder: 11,
    gradient: "from-amber-500 to-yellow-500",
  },
  {
    id: "engineering-practices",
    name: "Engineering Practices",
    description: "Software architecture, testing, and debugging methodologies.",
    icon: "ShieldCheck",
    displayOrder: 12,
    gradient: "from-slate-500 to-slate-700",
  },
];
