import { Technology } from "@/types";

export const technologies: Technology[] = [
  // --- FRONTEND ---
  {
    id: "nextjs15",
    slug: "next-js",
    name: "Next.js 15",
    fullName: "Next.js Web Framework",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/nextdotjs.svg",
    iconType: "image",
    creator: "Vercel",
    releaseYear: 2016,
    description: "Next.js is a production-ready React framework supporting Server Components, SSR, SSG, routing and API routes.",
    whyWeUseIt: [
      "Excellent SEO capabilities via SSR and static generation",
      "High performance with automatic code splitting and image optimization",
      "Robust file-based App Router architecture",
      "Seamless Vercel deployment and integration",
      "Exceptional developer experience with instant hot reloading"
    ],
    bestFor: [
      "SaaS Platforms",
      "Dynamic Dashboards",
      "Marketing Websites",
      "Admin Panels"
    ],
    officialWebsite: "https://nextjs.org",
    documentationUrl: "https://nextjs.org/docs",
    githubUrl: "https://github.com/vercel/next.js",
    relatedTechnologies: ["react19", "typescript", "tailwindcss", "vercel"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "Nexora Website"],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#000000"
  },
  {
    id: "react19",
    slug: "react",
    name: "React 19",
    fullName: "React UI Library",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/react.svg",
    iconType: "image",
    creator: "Meta",
    releaseYear: 2013,
    description: "React is a popular JavaScript library for building component-based, highly interactive and dynamic user interfaces.",
    whyWeUseIt: [
      "Declarative component-driven architecture",
      "Enormous ecosystem and rich community libraries",
      "Concurrent rendering capabilities",
      "Reusability of components across web and native mobile apps",
      "React 19 Server Actions and enhanced ref/context support"
    ],
    bestFor: [
      "Single Page Applications",
      "Complex User Interfaces",
      "Reusable UI Component Libraries",
      "Cross-platform Web Apps"
    ],
    officialWebsite: "https://react.dev",
    documentationUrl: "https://react.dev/reference/react",
    githubUrl: "https://github.com/facebook/react",
    relatedTechnologies: ["nextjs15", "typescript", "framer"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "Internal Tools"],
    isCore: true,
    status: "Stable",
    popularity: 98,
    color: "#61DAFB"
  },
  {
    id: "typescript",
    slug: "typescript",
    name: "TypeScript",
    fullName: "TypeScript Programming Language",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/typescript.svg",
    iconType: "image",
    creator: "Microsoft",
    releaseYear: 2012,
    description: "TypeScript is a strongly typed superset of JavaScript that compiles to plain JavaScript, providing build-time safety.",
    whyWeUseIt: [
      "Catch type bugs at compile-time instead of runtime",
      "Outstanding autocompletion and editor refactoring tools",
      "Self-documenting codebases for clean team collaboration",
      "Robust support for modern ESNext features",
      "Highly maintainable architectural patterns in large teams"
    ],
    bestFor: [
      "Enterprise Codebases",
      "Team Workspaces",
      "API Integration Validation",
      "SaaS and E-Commerce Frontends"
    ],
    officialWebsite: "https://www.typescriptlang.org",
    documentationUrl: "https://www.typescriptlang.org/docs/",
    githubUrl: "https://github.com/microsoft/TypeScript",
    relatedTechnologies: ["nextjs15", "react19", "nodejs"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "Nexora Website"],
    isCore: true,
    status: "Stable",
    popularity: 97,
    color: "#3178C6"
  },
  {
    id: "javascript",
    slug: "javascript",
    name: "JavaScript",
    fullName: "JavaScript Language",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/javascript.svg",
    iconType: "image",
    creator: "Netscape",
    releaseYear: 1995,
    description: "The core lightweight, interpreted scripting language used to implement interactive behavior across all modern web browsers.",
    whyWeUseIt: [
      "The native language of the web, supported by every browser",
      "Extremely versatile—can be used on clients, servers, and mobile devices",
      "Enormous community support and infinite utility resources",
      "Event-driven paradigm ideal for user interfaces"
    ],
    bestFor: [
      "Web Page Interactivity",
      "Client-side Scripting",
      "Rapid Prototyping",
      "Lightweight Automation"
    ],
    officialWebsite: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    relatedTechnologies: ["typescript", "nodejs", "react19"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["Legacy Systems", "Custom Scripts", "Client Integrations"],
    isCore: true,
    status: "Stable",
    popularity: 100,
    color: "#F7DF1E"
  },
  {
    id: "tailwindcss",
    slug: "tailwindcss",
    name: "Tailwind CSS",
    fullName: "Tailwind CSS Framework",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tailwindcss.svg",
    iconType: "image",
    creator: "Tailwind Labs",
    releaseYear: 2017,
    description: "A utility-first CSS framework for rapidly building custom, responsive user interfaces without writing raw stylesheets.",
    whyWeUseIt: [
      "Design components directly inside HTML classes",
      "Extremely small production bundles via PurgeCSS/built-in compiler",
      "Consistently enforces design tokens (spacing, fonts, colors)",
      "Excellent support for responsive and dark mode layout creation"
    ],
    bestFor: [
      "Rapid UI Prototyping",
      "SaaS Dashboards",
      "Responsive Layout Designs",
      "Design System Implementations"
    ],
    officialWebsite: "https://tailwindcss.com",
    documentationUrl: "https://tailwindcss.com/docs",
    githubUrl: "https://github.com/tailwindlabs/tailwindcss",
    relatedTechnologies: ["nextjs15", "react19", "shadcn"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "Nexora Website"],
    isCore: true,
    status: "Stable",
    popularity: 94,
    color: "#06B6D4"
  },
  {
    id: "alpinejs",
    slug: "alpinejs",
    name: "Alpine.js",
    fullName: "Alpine.js UI Framework",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/alpinedotjs.svg",
    iconType: "image",
    creator: "Caleb Porzio",
    releaseYear: 2019,
    description: "A rugged, minimal tool for composing behavior directly in your markup, providing reactive features at a fraction of the cost.",
    whyWeUseIt: [
      "Ultra-lightweight alternative to Vue/React for simple pages",
      "Write reactive behavior directly in HTML class/attribute tags",
      "Perfect companion for Laravel Blade layouts",
      "Extremely quick learning curve and zero build steps required"
    ],
    bestFor: [
      "Static Landing Pages",
      "Simple Dropdowns & Modals",
      "Laravel Blade Enhancements",
      "Micro-Interactivity"
    ],
    officialWebsite: "https://alpinejs.dev",
    documentationUrl: "https://alpinejs.dev/start",
    githubUrl: "https://github.com/alpinejs/alpine",
    relatedTechnologies: ["blade", "laravel12", "livewire"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: ["E-Commerce Frontends", "Custom Client Sites"],
    isCore: false,
    status: "Stable",
    popularity: 80,
    color: "#77C1D2"
  },
  {
    id: "blade",
    slug: "blade",
    name: "Blade Templates",
    fullName: "Laravel Blade Templating",
    categoryId: "frontend",
    logo: "layout",
    iconType: "lucide",
    creator: "Taylor Otwell",
    releaseYear: 2011,
    description: "The simple yet powerful templating engine provided with Laravel, allowing seamless integration of HTML and PHP.",
    whyWeUseIt: [
      "Compiles directly to plain PHP for zero execution overhead",
      "Clean template inheritance, sections, and component structures",
      "Provides secure directives preventing XSS injections automatically",
      "Excellent coordination with Alpine.js and Livewire"
    ],
    bestFor: [
      "Laravel Web Applications",
      "Server-Rendered Multi-page Apps",
      "Admin Interfaces",
      "Fast Prototyping inside Laravel"
    ],
    officialWebsite: "https://laravel.com/docs/master/blade",
    documentationUrl: "https://laravel.com/docs/master/blade",
    relatedTechnologies: ["laravel12", "alpinejs", "livewire"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: ["FinTech Admin Portal", "Client E-Commerce Products"],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#FF2E21"
  },

  // --- BACKEND ---
  {
    id: "laravel12",
    slug: "laravel",
    name: "Laravel 12",
    fullName: "Laravel MVC Framework",
    categoryId: "backend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/laravel.svg",
    iconType: "image",
    creator: "Taylor Otwell",
    releaseYear: 2011,
    description: "Laravel is a web application framework with expressive, elegant syntax, simplifying backend tasks like auth, routing, and queues.",
    whyWeUseIt: [
      "Robust ecosystem including Eloquent ORM, queues, and migration utilities",
      "First-class background worker queues and cron task schedulers",
      "Secure by design with built-in CSRF, SQLi, and authentication features",
      "Outstanding developer productivity and clean structure patterns",
      "Laravel 12 features built-in Vite compilation and advanced type-hints"
    ],
    bestFor: [
      "Robust Business APIs",
      "SaaS Core APIs",
      "Database Heavy Apps",
      "Real-time Queue Task Schedulers"
    ],
    officialWebsite: "https://laravel.com",
    documentationUrl: "https://laravel.com/docs/11.x",
    githubUrl: "https://github.com/laravel/laravel",
    relatedTechnologies: ["php82", "eloquent", "mysql", "redis"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "FinTech Mobile App", "Internal Admin Panel"],
    isCore: true,
    status: "Stable",
    popularity: 92,
    color: "#FF2E21"
  },
  {
    id: "php82",
    slug: "php",
    name: "PHP 8.2+",
    fullName: "PHP Hypertext Preprocessor",
    categoryId: "backend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/php.svg",
    iconType: "image",
    creator: "Rasmus Lerdorf",
    releaseYear: 1995,
    description: "A popular general-purpose scripting language suited to web development, offering modern typing, JIT compiling, and speed.",
    whyWeUseIt: [
      "Fast execution times with PHP 8 OPcache and JIT compilation",
      "Modern OOP features including Readonly classes, Enums, and Union types",
      "Powers Laravel, offering unmatched backend stability",
      "Massive ecosystem and universal hosting compatibility"
    ],
    bestFor: [
      "RESTful Backend APIs",
      "Server-side Application Logic",
      "CMS and Marketplace Platforms",
      "Enterprise Backends"
    ],
    officialWebsite: "https://www.php.net",
    documentationUrl: "https://www.php.net/docs.php",
    githubUrl: "https://github.com/php/php-src",
    relatedTechnologies: ["laravel12", "eloquent", "mysql"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform", "E-Commerce Marketplaces"],
    isCore: true,
    status: "Stable",
    popularity: 88,
    color: "#777BB4"
  },
  {
    id: "nodejs",
    slug: "nodejs",
    name: "Node.js",
    fullName: "Node.js JavaScript Runtime",
    categoryId: "backend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/nodedotjs.svg",
    iconType: "image",
    creator: "OpenJS Foundation",
    releaseYear: 2009,
    description: "An open-source, cross-platform JavaScript runtime built on Chrome's V8 engine for building fast, scalable network apps.",
    whyWeUseIt: [
      "Non-blocking, event-driven I/O model makes it highly efficient",
      "Allows developers to write JavaScript across both client and server",
      "Enormous npm ecosystem containing thousands of packages",
      "Perfect for building real-time microservices and websocket backends"
    ],
    bestFor: [
      "Real-time Chat Applications",
      "Microservices Architecture",
      "REST APIs & GraphQL Servers",
      "Build Tooling & CLI Utilities"
    ],
    officialWebsite: "https://nodejs.org",
    documentationUrl: "https://nodejs.org/en/docs/",
    githubUrl: "https://github.com/nodejs/node",
    relatedTechnologies: ["expressjs", "typescript", "javascript"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: ["Multi-Vendor E-Commerce", "FinTech Mobile App", "Image Processing Pipelines"],
    isCore: true,
    status: "Stable",
    popularity: 96,
    color: "#339933"
  },
  {
    id: "expressjs",
    slug: "expressjs",
    name: "Express.js",
    fullName: "Express.js Web Framework",
    categoryId: "backend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/express.svg",
    iconType: "image",
    creator: "TJ Holowaychuk",
    releaseYear: 2010,
    description: "A minimal and flexible Node.js web application framework, providing a robust set of features for web and mobile applications.",
    whyWeUseIt: [
      "Extremely thin layer of essential web application features",
      "Highly customizable middleware stack for routing, auth, and validation",
      "Excellent performance owing to its minimalist core structure",
      "De-facto standard framework for lightweight Node.js API development"
    ],
    bestFor: [
      "RESTful API Backends",
      "Microservices",
      "Gateway Routing Proxies",
      "Rapid backend prototyping"
    ],
    officialWebsite: "https://expressjs.com",
    documentationUrl: "https://expressjs.com/en/api.html",
    githubUrl: "https://github.com/expressjs/express",
    relatedTechnologies: ["nodejs", "typescript", "mongodb"],
    experienceLevel: "Supporting",
    difficulty: "Intermediate",
    usedInProjects: ["Multi-Vendor E-Commerce", "FinTech Mobile App"],
    isCore: false,
    status: "Stable",
    popularity: 90,
    color: "#000000"
  },
  {
    id: "livewire",
    slug: "livewire",
    name: "Livewire",
    fullName: "Laravel Livewire Framework",
    categoryId: "backend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/livewire.svg",
    iconType: "image",
    creator: "Caleb Porzio",
    releaseYear: 2019,
    description: "A full-stack framework for Laravel that makes building dynamic interfaces simple, without leaving the comfort of Laravel.",
    whyWeUseIt: [
      "Build interactive UIs without writing custom JavaScript",
      "Maintains UI state via secure, automated server roundtrips",
      "Integrates fully with Laravel Blade, Eloquent, and validation rules",
      "Greatly reduces frontend-backend code separation complexity"
    ],
    bestFor: [
      "Laravel Admin Panels",
      "Complex Multi-step Forms",
      "Dynamic Dashboards",
      "CRUD Interfaces"
    ],
    officialWebsite: "https://livewire.laravel.com",
    documentationUrl: "https://livewire.laravel.com/docs",
    githubUrl: "https://github.com/livewire/livewire",
    relatedTechnologies: ["laravel12", "alpinejs", "blade"],
    experienceLevel: "Supporting",
    difficulty: "Intermediate",
    usedInProjects: ["FinTech Admin Panel", "Internal Client Tools"],
    isCore: false,
    status: "Stable",
    popularity: 82,
    color: "#FB70A9"
  },
  {
    id: "server-actions",
    slug: "nextjs-server-actions",
    name: "Next.js Server Actions",
    fullName: "Next.js Server Actions",
    categoryId: "backend",
    logo: "zap",
    iconType: "lucide",
    creator: "Vercel",
    releaseYear: 2023,
    description: "Asynchronous server functions that can be called directly from React Client components, bypassing manual API routes.",
    whyWeUseIt: [
      "Eliminates the need to write boilerplate fetch/REST endpoints",
      "Fully type-safe client-to-server communications",
      "Built-in support for form submissions and optimistic updates",
      "Enables server-side database mutation logic directly from UIs"
    ],
    bestFor: [
      "Form submissions in Next.js",
      "Direct database mutations",
      "Type-safe client-server interactions",
      "Quick button trigger operations"
    ],
    officialWebsite: "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations",
    documentationUrl: "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations",
    relatedTechnologies: ["nextjs15", "react19", "prisma"],
    experienceLevel: "Primary",
    difficulty: "Advanced",
    usedInProjects: ["SaaS Platform", "Nexora Website"],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#000000"
  },

  // --- DATABASE ---
  {
    id: "mysql",
    slug: "mysql",
    name: "MySQL",
    fullName: "MySQL Relational Database",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mysql.svg",
    iconType: "image",
    creator: "Oracle",
    releaseYear: 1995,
    description: "MySQL is an open-source relational database management system, renowned for its reliability and ACID compliance.",
    whyWeUseIt: [
      "Industry standard reliability and rock-solid ACID transactions",
      "Extremely fast read speeds and optimized indexing patterns",
      "Default database choice for Laravel applications",
      "Easy scaling with replication and connection pooling tools"
    ],
    bestFor: [
      "E-Commerce Systems",
      "Relational Data Records",
      "CMS Backends",
      "Standard Web Applications"
    ],
    officialWebsite: "https://www.mysql.com",
    documentationUrl: "https://dev.mysql.com/doc/",
    relatedTechnologies: ["laravel12", "eloquent", "postgresql"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform", "Internal Admin Panel", "Customer Portals"],
    isCore: true,
    status: "Stable",
    popularity: 91,
    color: "#4479A1"
  },
  {
    id: "postgresql",
    slug: "postgresql",
    name: "PostgreSQL",
    fullName: "PostgreSQL Relational Database",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/postgresql.svg",
    iconType: "image",
    creator: "PostgreSQL Global Development Group",
    releaseYear: 1996,
    description: "PostgreSQL is a powerful, open-source object-relational database system, praised for its extensibility and SQL compliance.",
    whyWeUseIt: [
      "Advanced indexing features (GIN, GiST, BRIN) for high-perf queries",
      "Exceptional support for JSONB structured query searches",
      "Rich geospatial features via the PostGIS extension",
      "Highly robust concurrency controls and transaction integrity"
    ],
    bestFor: [
      "Complex Financial Backends",
      "Geospatial Mapping Engines",
      "High Concurrency Platforms",
      "JSON Document/Relational hybrids"
    ],
    officialWebsite: "https://www.postgresql.org",
    documentationUrl: "https://www.postgresql.org/docs/",
    githubUrl: "https://github.com/postgres/postgres",
    relatedTechnologies: ["supabase", "prisma", "nodejs"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: ["FinTech Mobile App", "SaaS Platform APIs", "Analytical Dashboards"],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#4169E1"
  },
  {
    id: "mongodb",
    slug: "mongodb",
    name: "MongoDB",
    fullName: "MongoDB Document Database",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mongodb.svg",
    iconType: "image",
    creator: "MongoDB Inc.",
    releaseYear: 2009,
    description: "A general-purpose, document-based NoSQL database designed for modern app developers and the cloud era.",
    whyWeUseIt: [
      "Flexible schema design allows rapid changes to data structures",
      "Highly scalable horizontal sharding out of the box",
      "Native JSON-like BSON documents align perfectly with Node.js objects",
      "Outstanding query aggregation pipeline for analytics"
    ],
    bestFor: [
      "Content Management Systems",
      "Real-time Big Data Analytics",
      "User Profiles & Sessions Stores",
      "Rapidly Evolving Schema Apps"
    ],
    officialWebsite: "https://www.mongodb.com",
    documentationUrl: "https://www.mongodb.com/docs/",
    githubUrl: "https://github.com/mongodb/mongo",
    relatedTechnologies: ["nodejs", "expressjs"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: ["Notification Microservices", "Activity Logs Hub"],
    isCore: false,
    status: "Stable",
    popularity: 89,
    color: "#47A248"
  },
  {
    id: "redis",
    slug: "redis",
    name: "Redis",
    fullName: "Redis In-Memory Database",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/redis.svg",
    iconType: "image",
    creator: "Salvatore Sanfilippo",
    releaseYear: 2009,
    description: "Redis is an open-source, in-memory data structure store used as a database, cache, and message broker.",
    whyWeUseIt: [
      "Sub-millisecond data read/write latency using in-memory execution",
      "Supports complex structures (hashes, lists, sets, sorted sets)",
      "Excellent pub/sub messaging features for real-time operations",
      "Built-in expiring cache key controls"
    ],
    bestFor: [
      "Application Caching Layer",
      "Web Session Management",
      "Real-time Leaderboards",
      "Rate Limiters & Job Queues"
    ],
    officialWebsite: "https://redis.io",
    documentationUrl: "https://redis.io/documentation",
    githubUrl: "https://github.com/redis/redis",
    relatedTechnologies: ["laravel12", "nodejs", "postgresql"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "E-Commerce Cart Cache", "Queue Processing System"],
    isCore: true,
    status: "Stable",
    popularity: 93,
    color: "#FF3E30"
  },
  {
    id: "neo4j",
    slug: "neo4j",
    name: "Neo4j",
    fullName: "Neo4j Graph Database",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/neo4j.svg",
    iconType: "image",
    creator: "Neo4j Inc.",
    releaseYear: 2007,
    description: "A highly scalable native graph database management system designed to leverage data relationships.",
    whyWeUseIt: [
      "Query complex relations infinitely faster than SQL JOINs",
      "Highly expressive Cypher query language designed for graphs",
      "Accurately maps interconnected nodes (e.g., users, transactions)",
      "Extremely robust database transaction logging"
    ],
    bestFor: [
      "Social Network Connections",
      "Recommendation Systems",
      "Fraud Detection Analytics",
      "Network Dependency Mapping"
    ],
    officialWebsite: "https://neo4j.com",
    documentationUrl: "https://neo4j.com/docs/",
    githubUrl: "https://github.com/neo4j/neo4j",
    relatedTechnologies: ["nodejs", "postgresql"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: ["Internal Knowledge Mapping", "Fraud Analytics Dashboard"],
    isCore: false,
    status: "Stable",
    popularity: 76,
    color: "#008CC1"
  },
  {
    id: "prisma",
    slug: "prisma",
    name: "Prisma ORM",
    fullName: "Prisma Database Toolkit",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/prisma.svg",
    iconType: "image",
    creator: "Prisma",
    releaseYear: 2019,
    description: "An open-source next-generation ORM for Node.js and TypeScript, making database access intuitive and type-safe.",
    whyWeUseIt: [
      "Automatically generates complete TypeScript types from schema models",
      "Highly intuitive schema definition syntax",
      "Automated and secure database migrations engine",
      "Outstanding query autocomplete inside modern IDEs"
    ],
    bestFor: [
      "TypeScript Web Applications",
      "Type-safe APIs in Node.js",
      "Next.js databases",
      "Clean DB Schema Migrations"
    ],
    officialWebsite: "https://www.prisma.io",
    documentationUrl: "https://www.prisma.io/docs",
    githubUrl: "https://github.com/prisma/prisma",
    relatedTechnologies: ["typescript", "postgresql", "nextjs15"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["Multi-Vendor E-Commerce", "Internal Client Dashboards"],
    isCore: true,
    status: "Stable",
    popularity: 91,
    color: "#2D3748"
  },
  {
    id: "drizzle",
    slug: "drizzle",
    name: "Drizzle ORM",
    fullName: "Drizzle ORM for TS",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/drizzle.svg",
    iconType: "image",
    creator: "Drizzle Team",
    releaseYear: 2022,
    description: "A lightweight TypeScript ORM that runs in serverless, edge, and cloud flare environments, focusing on raw SQL compatibility.",
    whyWeUseIt: [
      "Zero overhead—feels like raw SQL but with full type safety",
      "Perfect for Cloudflare Workers and Edge runtimes",
      "Fastest typescript ORM on the market with tiny bundle footprints",
      "Explicit relationships and simple query builders"
    ],
    bestFor: [
      "Serverless Database Queries",
      "High-Performance Edge Apps",
      "Lightweight TS Backends",
      "Cloudflare Workers Projects"
    ],
    officialWebsite: "https://orm.drizzle.team",
    documentationUrl: "https://orm.drizzle.team/docs/overview",
    githubUrl: "https://github.com/drizzle-team/drizzle-orm",
    relatedTechnologies: ["typescript", "postgresql", "supabase"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: ["Edge APIs", "Serverless Functions"],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#C5F82A"
  },
  {
    id: "eloquent",
    slug: "eloquent-orm",
    name: "Eloquent ORM",
    fullName: "Laravel Eloquent ORM",
    categoryId: "database",
    logo: "database",
    iconType: "lucide",
    creator: "Taylor Otwell",
    releaseYear: 2011,
    description: "The Active Record ORM implementation included with Laravel, providing beautiful object-oriented database interactions.",
    whyWeUseIt: [
      "Incredibly clean syntax for querying related tables",
      "Native support for model events, global scopes, and mutators",
      "Built-in query pagination and dynamic attribute casting",
      "Integrates perfectly with Laravel Migrations"
    ],
    bestFor: [
      "Laravel Database Operations",
      "Active Record Modeling",
      "Rapid Database Prototyping",
      "Complex Model Relationships"
    ],
    officialWebsite: "https://laravel.com/docs/master/eloquent",
    documentationUrl: "https://laravel.com/docs/master/eloquent",
    relatedTechnologies: ["laravel12", "php82", "mysql"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform Backend", "FinTech Admin Portal"],
    isCore: true,
    status: "Stable",
    popularity: 90,
    color: "#FF2E21"
  },

  // --- CLOUD ---
  {
    id: "supabase",
    slug: "supabase",
    name: "Supabase",
    fullName: "Supabase Open Source Firebase Alternative",
    categoryId: "cloud",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/supabase.svg",
    iconType: "image",
    creator: "Supabase",
    releaseYear: 2020,
    description: "An open source Firebase alternative providing a Postgres database, Authentication, instant APIs, Edge Functions and Realtime.",
    whyWeUseIt: [
      "Provides a real PostgreSQL database with full SQL control",
      "Instant REST/Websocket APIs generated automatically from database tables",
      "Outstanding, secure Row-Level Security (RLS) configuration",
      "Built-in Auth, Storage bucket files management and Edge Functions"
    ],
    bestFor: [
      "Rapid MVP Development",
      "Real-time Applications",
      "Serverless Mobile Backends",
      "Next.js Database Integration"
    ],
    officialWebsite: "https://supabase.com",
    documentationUrl: "https://supabase.com/docs",
    githubUrl: "https://github.com/supabase/supabase",
    relatedTechnologies: ["postgresql", "nextjs15", "react19"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["Multi-Vendor E-Commerce Marketplace", "Internal Client Tools"],
    isCore: true,
    status: "Stable",
    popularity: 93,
    color: "#3ECF8E"
  },
  {
    id: "firebase",
    slug: "firebase",
    name: "Firebase",
    fullName: "Google Firebase Suite",
    categoryId: "cloud",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/firebase.svg",
    iconType: "image",
    creator: "Google",
    releaseYear: 2011,
    description: "Firebase is Google's mobile application development platform, offering databases, analytics, auth and cloud messaging.",
    whyWeUseIt: [
      "Ultra-low latency Realtime Database and Firestore syncing",
      "Seamless integration with Google Analytics and Crashlytics utilities",
      "Industry-leading Push Notifications via FCM (Firebase Cloud Messaging)",
      "Instant, reliable Auth configuration supporting social OAuth logins"
    ],
    bestFor: [
      "Mobile App Push Notifications",
      "Real-time Document Storage",
      "Quick Prototyping",
      "Analytics Integrations"
    ],
    officialWebsite: "https://firebase.google.com",
    documentationUrl: "https://firebase.google.com/docs",
    githubUrl: "https://github.com/firebase/firebase-js-sdk",
    relatedTechnologies: ["android-studio", "supabase"],
    experienceLevel: "Advanced",
    difficulty: "Beginner",
    usedInProjects: ["FinTech Mobile App (FCM)", "Mobile App Chat Syncer"],
    isCore: false,
    status: "Stable",
    popularity: 90,
    color: "#FFCA28"
  },
  {
    id: "appwrite",
    slug: "appwrite",
    name: "Appwrite",
    fullName: "Appwrite Backend Suite",
    categoryId: "cloud",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/appwrite.svg",
    iconType: "image",
    creator: "Appwrite",
    releaseYear: 2019,
    description: "Appwrite is an open-source backend-as-a-service packaged as a set of Docker microservices, simplifying app creation.",
    whyWeUseIt: [
      "Can be easily self-hosted on a single virtual server using Docker",
      "Provides database, authentication, storage, functions, and localization features",
      "Clean SDKs available for web, server, Flutter, Android, and iOS",
      "Active open-source development community"
    ],
    bestFor: [
      "Self-hosted BaaS Platforms",
      "Cross-platform App Backends",
      "Privacy-conscious Cloud Apps",
      "Docker Local Dev Environments"
    ],
    officialWebsite: "https://appwrite.io",
    documentationUrl: "https://appwrite.io/docs",
    githubUrl: "https://github.com/appwrite/appwrite",
    relatedTechnologies: ["docker", "supabase"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: ["Internal Prototyping Sandbox"],
    isCore: false,
    status: "Stable",
    popularity: 81,
    color: "#FD366E"
  },
  {
    id: "vercel",
    slug: "vercel",
    name: "Vercel",
    fullName: "Vercel Cloud Deployment",
    categoryId: "cloud",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/vercel.svg",
    iconType: "image",
    creator: "Vercel",
    releaseYear: 2015,
    description: "Vercel is the optimal hosting platform for frontend frameworks, offering instant CI/CD serverless deployments and edge routing.",
    whyWeUseIt: [
      "Automated git-integrated staging and production preview links",
      "Zero-configuration deployments for Next.js, Vite, and React",
      "Ultra-fast Global CDN network and edge functions execution",
      "Outstanding built-in web analytics and speed insights dashboards"
    ],
    bestFor: [
      "Next.js App Deployment",
      "Serverless Frontends",
      "Global CDN Distribution",
      "Static Landing Pages"
    ],
    officialWebsite: "https://vercel.com",
    documentationUrl: "https://vercel.com/docs",
    githubUrl: "https://github.com/vercel/vercel",
    relatedTechnologies: ["nextjs15", "react19", "github"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform Frontend", "Nexora Website", "Client Web Portals"],
    isCore: true,
    status: "Stable",
    popularity: 97,
    color: "#000000"
  },

  // --- DEVOPS ---
  {
    id: "docker",
    slug: "docker",
    name: "Docker",
    fullName: "Docker Containerization",
    categoryId: "devops",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/docker.svg",
    iconType: "image",
    creator: "Docker Inc.",
    releaseYear: 2013,
    description: "Docker is an open platform for developing, shipping, and running applications inside lightweight, isolated containers.",
    whyWeUseIt: [
      "Ensures absolute consistency across local, staging, and production environments",
      "Eliminates the 'works on my machine' class of server runtime issues",
      "Easily packages multi-container architectures using Docker Compose",
      "Provides isolation for background workers and microservices"
    ],
    bestFor: [
      "Local Development Virtualization",
      "Microservice Architectures",
      "CI/CD Pipeline Building",
      "Consistent Server Configurations"
    ],
    officialWebsite: "https://www.docker.com",
    documentationUrl: "https://docs.docker.com",
    githubUrl: "https://github.com/docker/docker-ce",
    relatedTechnologies: ["nginx", "github", "laravel12"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "E-Commerce Marketplace", "Dev Environments"],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#2496ED"
  },
  {
    id: "nginx",
    slug: "nginx",
    name: "Nginx",
    fullName: "Nginx Web Server",
    categoryId: "devops",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/nginx.svg",
    iconType: "image",
    creator: "Igor Sysoev",
    releaseYear: 2004,
    description: "Nginx is a high-performance HTTP web server, reverse proxy, load balancer, and mail proxy server.",
    whyWeUseIt: [
      "Extremely high concurrency capability handling thousands of connections",
      "Efficient reverse proxy routing and SSL/TLS certificate offloading",
      "Serves static assets at incredible speeds with low CPU overhead",
      "De-facto standard gatekeeper server for PHP-FPM/Laravel backends"
    ],
    bestFor: [
      "Reverse Proxy Configurations",
      "Load Balancing Web Traffic",
      "SSL Certificate Termination",
      "Serving Static HTML/CSS Files"
    ],
    officialWebsite: "https://nginx.org",
    documentationUrl: "https://nginx.org/en/docs/",
    githubUrl: "https://github.com/nginx/nginx",
    relatedTechnologies: ["docker", "laravel12", "apache"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: ["Production Client APIs", "Custom Reverse Proxy Gateways"],
    isCore: true,
    status: "Stable",
    popularity: 90,
    color: "#009639"
  },
  {
    id: "apache",
    slug: "apache-http-server",
    name: "Apache",
    fullName: "Apache HTTP Server",
    categoryId: "devops",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/apache.svg",
    iconType: "image",
    creator: "Apache Software Foundation",
    releaseYear: 1995,
    description: "A time-tested, open-source HTTP server that powers a significant portion of the internet with modular configuration.",
    whyWeUseIt: [
      "Includes `.htaccess` configuration files for dynamic folder control",
      "Extremely robust module configuration (mod_rewrite, mod_ssl)",
      "High reliability with a massive community support framework",
      "Native compatibility with legacy client server setups"
    ],
    bestFor: [
      "Dynamic Server Directories",
      "Shared Web Hosting setups",
      "Legacy PHP Applications",
      "Configurable Local Environments"
    ],
    officialWebsite: "https://httpd.apache.org",
    documentationUrl: "https://httpd.apache.org/docs/",
    relatedTechnologies: ["nginx", "php82"],
    experienceLevel: "Supporting",
    difficulty: "Intermediate",
    usedInProjects: ["Legacy Client Migrations"],
    isCore: false,
    status: "Stable",
    popularity: 78,
    color: "#D22128"
  },
  {
    id: "queue-supervisor",
    slug: "supervisor-queue-processing",
    name: "Queue Processing (Supervisor)",
    fullName: "Supervisor Daemon",
    categoryId: "devops",
    logo: "cpu",
    iconType: "lucide",
    creator: "Community",
    releaseYear: 2004,
    description: "A client/server system that allows users to monitor and control a number of processes on UNIX-like operating systems.",
    whyWeUseIt: [
      "Keeps Laravel queue worker processes running permanently in background",
      "Automatically restarts queue workers if they exit unexpectedly",
      "Easy scaling of background processing by running multiple worker threads",
      "Detailed error logs and CPU/memory footprint containment"
    ],
    bestFor: [
      "Running Laravel Queue Workers",
      "Keeping Long-Running Node scripts alive",
      "Process monitoring on Linux",
      "Self-healing background services"
    ],
    officialWebsite: "http://supervisord.org",
    documentationUrl: "http://supervisord.org",
    githubUrl: "https://github.com/Supervisor/supervisor",
    relatedTechnologies: ["laravel12", "docker"],
    experienceLevel: "Supporting",
    difficulty: "Advanced",
    usedInProjects: ["SaaS Platform Queue Schedulers", "Image Processing Pipelines"],
    isCore: false,
    status: "Stable",
    popularity: 82,
    color: "#4F46E5"
  },
  {
    id: "debug",
    slug: "production-debugging",
    name: "Production Debugging",
    fullName: "Production System Debugging",
    categoryId: "devops",
    logo: "bug",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Methods and frameworks for safe diagnostic testing, logs tracking, and bug identification in live systems.",
    whyWeUseIt: [
      "Find performance bottlenecks and logic errors without breaking live sites",
      "Safe logging patterns that strip private user data (PII)",
      "Enables continuous deployment with rapid fallback protocols",
      "Helps maintain 99.9% application uptime"
    ],
    bestFor: [
      "Live API Error Tracking",
      "Database Query Bottleneck Audits",
      "Server Memory Leak Detection",
      "Incident Resolution"
    ],
    officialWebsite: "https://sentry.io",
    documentationUrl: "https://sentry.io/docs/",
    relatedTechnologies: ["monitoring", "github"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "FinTech Mobile App"],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#DC2626"
  },
  {
    id: "monitoring",
    slug: "error-monitoring",
    name: "Error Monitoring",
    fullName: "Real-time Error Monitoring",
    categoryId: "devops",
    logo: "activity",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2010,
    description: "Integrating error tracking services (like Sentry, LogRocket, or Datadog) to alert developers to real-time client/server errors.",
    whyWeUseIt: [
      "Alerts the dev team to bugs BEFORE customers report them",
      "Aggregates stack traces, client device states, and session events",
      "Measures Core Web Vitals and performance health metrics",
      "Identifies recurring code issues in production builds"
    ],
    bestFor: [
      "Automated Bug Alerts",
      "Performance Health Dashboards",
      "Client Session Replays",
      "Real-time Incident Tracking"
    ],
    officialWebsite: "https://sentry.io",
    documentationUrl: "https://docs.sentry.io",
    relatedTechnologies: ["debug", "vercel"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "FinTech Mobile App"],
    isCore: false,
    status: "Stable",
    popularity: 90,
    color: "#2563EB"
  },
  {
    id: "build-opt",
    slug: "build-optimization",
    name: "Build Optimization",
    fullName: "Assets & Code Build Optimization",
    categoryId: "devops",
    logo: "zap",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2015,
    description: "Techniques for bundling code, compressing assets, lazy-loading imports, and utilizing tree-shaking to speed up sites.",
    whyWeUseIt: [
      "Drastically reduces Javascript bundle sizes for mobile visitors",
      "Improves Lighthouse and PageSpeed score targets above 95",
      "Lowers server bandwidth usage and hosting transfer costs",
      "Ensures immediate page responsiveness on slow mobile connections"
    ],
    bestFor: [
      "Lighthouse Score Auditing",
      "E-Commerce Mobile Conversions",
      "Fast Content Delivery",
      "Asset Size Reductions"
    ],
    officialWebsite: "https://web.dev/fast/",
    documentationUrl: "https://web.dev/fast/",
    relatedTechnologies: ["nextjs15", "vite", "tailwindcss"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: ["Nexora Website", "Multi-Vendor E-Commerce", "SaaS Platform"],
    isCore: false,
    status: "Stable",
    popularity: 87,
    color: "#16A34A"
  },

  // --- AUTHENTICATION ---
  {
    id: "auth-system",
    slug: "authentication-system",
    name: "Authentication & Authorization",
    fullName: "Security Authentication Standards",
    categoryId: "authentication",
    logo: "lock",
    iconType: "lucide",
    creator: "Nexora",
    releaseYear: 2021,
    description: "Industry-standard protocols (JWT, OAuth, Session tokens, MFA) that verify user identity and protect API endpoints.",
    whyWeUseIt: [
      "Shields sensitive business data from unauthorized access",
      "Provides frictionless Multi-Factor Authentication (MFA)",
      "Supports SSO and OAuth logins (Google, Microsoft, GitHub)",
      "Enforces strict session invalidation and token refresh protocols"
    ],
    bestFor: [
      "User Sign-In Portals",
      "Secure SaaS API Access",
      "Financial Apps",
      "Customer Data Isolation"
    ],
    officialWebsite: "https://oauth.net/2/",
    documentationUrl: "https://oauth.net/2/",
    relatedTechnologies: ["rbac", "supabase", "laravel12"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "FinTech Mobile App"],
    isCore: true,
    status: "Stable",
    popularity: 96,
    color: "#0F172A"
  },
  {
    id: "rbac",
    slug: "role-based-access-control",
    name: "RBAC",
    fullName: "Role-Based Access Control",
    categoryId: "authentication",
    logo: "shield-check",
    iconType: "lucide",
    creator: "NIST",
    releaseYear: 1992,
    description: "Granting system access permissions to authorized users based on roles (admin, manager, viewer) within an organization.",
    whyWeUseIt: [
      "Enforces the Principle of Least Privilege across complex dashboards",
      "Easily configurable role-to-permission database schemas",
      "Simplifies user onboarding by grouping permissions into roles",
      "Essential compliance requirement for SOC2 and HIPAA standards"
    ],
    bestFor: [
      "Multi-Tenant SaaS Platforms",
      "Corporate Back-Office Portals",
      "FinTech Security Audits",
      "E-Commerce Vendor Portals"
    ],
    officialWebsite: "https://csrc.nist.gov/projects/role-based-access-control",
    documentationUrl: "https://csrc.nist.gov/projects/role-based-access-control",
    relatedTechnologies: ["auth-system", "laravel12", "supabase"],
    experienceLevel: "Core",
    difficulty: "Advanced",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "FinTech Admin Portal"],
    isCore: true,
    status: "Stable",
    popularity: 92,
    color: "#1E293B"
  },
  {
    id: "csp",
    slug: "content-security-policy",
    name: "Security Headers (CSP)",
    fullName: "Content Security Policy Headers",
    categoryId: "authentication",
    logo: "shield",
    iconType: "lucide",
    creator: "W3C",
    releaseYear: 2012,
    description: "An added layer of security that helps detect and mitigate certain types of attacks, including Cross-Site Scripting (XSS) and data injection.",
    whyWeUseIt: [
      "Blocks unauthorized scripts, stylesheets, and iframe contents from loading",
      "Prevents dangerous form data hijacking and clickjacking",
      "Submits automated warnings to error logging backends during header violations",
      "Increases website security audit ratings to A+ grades"
    ],
    bestFor: [
      "Preventing XSS Injections",
      "Securing E-Commerce Payments",
      "HIPAA/GDPR Compliance",
      "Client Trust Verification"
    ],
    officialWebsite: "https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP",
    relatedTechnologies: ["auth-system", "nginx", "vercel"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: ["FinTech Mobile App Backend", "SaaS Platform API Layer"],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#16A34A"
  },

  // --- ARCHITECTURE ---
  {
    id: "rest-apis",
    slug: "rest-apis",
    name: "REST APIs",
    fullName: "RESTful API Architecture",
    categoryId: "architecture",
    logo: "globe",
    iconType: "lucide",
    creator: "Roy Fielding",
    releaseYear: 2000,
    description: "An architectural style for designing networked applications, relying on stateless, client-server, cacheable communications.",
    whyWeUseIt: [
      "Universal design standard understood by all developers and SDKs",
      "Stateless operations allow servers to scale horizontally",
      "Caching of GET requests speeds up repeat web visits",
      "Decoupled architecture splits client and server work cleanly"
    ],
    bestFor: [
      "Public Developer APIs",
      "Mobile App Backends",
      "Server-to-Server communication",
      "Microservice Endpoints"
    ],
    officialWebsite: "https://restfulapi.net",
    documentationUrl: "https://restfulapi.net",
    relatedTechnologies: ["nodejs", "laravel12", "expressjs"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "FinTech Mobile App"],
    isCore: true,
    status: "Stable",
    popularity: 99,
    color: "#0F172A"
  },
  {
    id: "webhooks",
    slug: "webhooks",
    name: "Webhooks",
    fullName: "Webhooks Event Pipeline",
    categoryId: "architecture",
    logo: "webhook",
    iconType: "lucide",
    creator: "Jeff Lindsay",
    releaseYear: 2007,
    description: "User-defined HTTP callbacks triggered by specific events (like successful payments), sending real-time data payloads.",
    whyWeUseIt: [
      "Enables real-time push events without constant client API polling",
      "Extremely resource-friendly, triggering only on verified events",
      "Critical for processing Stripe or Razorpay credit/debit payments",
      "Automates notification emails and invoice systems"
    ],
    bestFor: [
      "Payment Gateway Events",
      "SaaS Notification Triggers",
      "Third-party integrations",
      "Asynchronous tasks queueing"
    ],
    officialWebsite: "https://en.wikipedia.org/wiki/Webhook",
    documentationUrl: "https://en.wikipedia.org/wiki/Webhook",
    relatedTechnologies: ["razorpay", "laravel12", "nodejs"],
    experienceLevel: "Supporting",
    difficulty: "Intermediate",
    usedInProjects: ["Multi-Vendor E-Commerce (Razorpay Webhooks)", "SaaS Stripe Integration"],
    isCore: false,
    status: "Stable",
    popularity: 90,
    color: "#6366F1"
  },
  {
    id: "schema-design",
    slug: "database-schema-design",
    name: "Database Schema Design",
    fullName: "Relational & NoSQL Schema Design",
    categoryId: "architecture",
    logo: "network",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 1970,
    description: "Designing the logical architecture, tables, fields, constraints, and relationships of databases to ensure high performance and integrity.",
    whyWeUseIt: [
      "Eliminates duplicate storage using strict database normalization",
      "Speeds up database queries using optimized indexes",
      "Enforces data integrity using Foreign Key constraints",
      "Prevents costly database rewrites as applications expand"
    ],
    bestFor: [
      "E-Commerce Data Catalogs",
      "Multi-Tenant SaaS data layouts",
      "Transactional Ledgers",
      "High Volume Storage planning"
    ],
    officialWebsite: "https://en.wikipedia.org/wiki/Database_schema",
    documentationUrl: "https://en.wikipedia.org/wiki/Database_schema",
    relatedTechnologies: ["postgresql", "mysql", "mongodb"],
    experienceLevel: "Core",
    difficulty: "Advanced",
    usedInProjects: ["SaaS Platform Schema", "Multi-Vendor E-Commerce DB Schema"],
    isCore: true,
    status: "Stable",
    popularity: 93,
    color: "#2563EB"
  },
  {
    id: "query-opt",
    slug: "query-optimization",
    name: "Query Optimization",
    fullName: "Database Query Optimization",
    categoryId: "architecture",
    logo: "gauge",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 1980,
    description: "Refining SQL queries, indexing strategies, and database setups to reduce response times and system overhead.",
    whyWeUseIt: [
      "Reduces slow query durations from seconds to milliseconds",
      "Prevents database locks during high-traffic checkout events",
      "Lowers cloud database CPU/Memory usage and subscription costs",
      "Maintains UI speed during massive page loading requests"
    ],
    bestFor: [
      "Large E-Commerce Product Searches",
      "Analytical Dashboard reports",
      "Resolving DB Connection Bottlenecks",
      "High Traffic scaling"
    ],
    officialWebsite: "https://en.wikipedia.org/wiki/Query_optimization",
    documentationUrl: "https://en.wikipedia.org/wiki/Query_optimization",
    relatedTechnologies: ["postgresql", "mysql", "redis"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: ["SaaS Reports Exporter", "Multi-Vendor E-Commerce Product Catalog"],
    isCore: false,
    status: "Stable",
    popularity: 89,
    color: "#EAB308"
  },
  {
    id: "inventory-systems",
    slug: "order-inventory-systems",
    name: "Order & Inventory Systems",
    fullName: "Transactional Order & Inventory Systems",
    categoryId: "architecture",
    logo: "package",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Designing reliable pipelines for order placements, database locks, stock updates, and shipping logs without race conditions.",
    whyWeUseIt: [
      "Prevents double-selling items using strict database row-level locking",
      "Maintains exact accounting audits for all inventory movements",
      "Automates notifications for low stock alerts",
      "Coordinates vendor orders across multi-channel setups"
    ],
    bestFor: [
      "Multi-Vendor marketplaces",
      "SaaS Subscription tracking",
      "Automated stock level management",
      "Warehouse tracking"
    ],
    officialWebsite: "https://en.wikipedia.org/wiki/Inventory_control",
    documentationUrl: "https://en.wikipedia.org/wiki/Inventory_control",
    relatedTechnologies: ["postgresql", "mysql", "redis"],
    experienceLevel: "Supporting",
    difficulty: "Advanced",
    usedInProjects: ["Multi-Vendor E-Commerce Marketplace"],
    isCore: false,
    status: "Stable",
    popularity: 84,
    color: "#F97316"
  },

  // --- SEARCH ---
  {
    id: "scout",
    slug: "laravel-scout",
    name: "Laravel Scout",
    fullName: "Laravel Scout Driver",
    categoryId: "search",
    logo: "search",
    iconType: "lucide",
    creator: "Taylor Otwell",
    releaseYear: 2016,
    description: "Laravel Scout provides a simple, driver-based solution for adding full-text search to your database models.",
    whyWeUseIt: [
      "Automatically synchronizes search indexes during database model mutations",
      "Seamlessly integrates with Meilisearch and Algolia",
      "Replaces slow, complex SQL LIKE queries with fast search indexing",
      "Extremely clean, Laravel-native syntax wrapper"
    ],
    bestFor: [
      "Laravel Model Search",
      "Instant Auto-completing search boxes",
      "E-Commerce Catalog Searches",
      "Admin Panel searches"
    ],
    officialWebsite: "https://laravel.com/docs/master/scout",
    documentationUrl: "https://laravel.com/docs/master/scout",
    relatedTechnologies: ["laravel12", "meilisearch", "algolia"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: ["Client Products Finder", "Admin Dashboard search"],
    isCore: false,
    status: "Stable",
    popularity: 86,
    color: "#FF2E21"
  },
  {
    id: "meilisearch",
    slug: "meilisearch",
    name: "Meilisearch",
    fullName: "Meilisearch Engine",
    categoryId: "search",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/meilisearch.svg",
    iconType: "image",
    creator: "Meilisearch",
    releaseYear: 2018,
    description: "An open-source, lightning-fast search engine written in Rust, offering immediate typo-tolerant search results.",
    whyWeUseIt: [
      "Delivers search results in under 50 milliseconds",
      "Outstanding, highly customizable typo tolerance out of the box",
      "Can be easily self-hosted to avoid expensive cloud subscription bills",
      "Supports synonyms, sorting, custom ranking rules and multi-tenant filters"
    ],
    bestFor: [
      "E-Commerce Product Searches",
      "In-App Documentation Searches",
      "Fast Autocomplete inputs",
      "Self-hosted search hubs"
    ],
    officialWebsite: "https://www.meilisearch.com",
    documentationUrl: "https://docs.meilisearch.com",
    githubUrl: "https://github.com/meilisearch/meilisearch",
    relatedTechnologies: ["scout", "laravel12", "nodejs"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: ["Multi-Vendor E-Commerce (Product Search)"],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#FF5C5C"
  },
  {
    id: "algolia",
    slug: "algolia",
    name: "Algolia",
    fullName: "Algolia Cloud Search",
    categoryId: "search",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/algolia.svg",
    iconType: "image",
    creator: "Algolia",
    releaseYear: 2012,
    description: "A premium cloud-based Search-as-a-Service platform, offering global index distribution, analytics, and recommendation API pipelines.",
    whyWeUseIt: [
      "Zero server setup required—fully managed cloud search infrastructure",
      "Global query routing ensures sub-10ms results anywhere in the world",
      "In-depth analytics highlighting search terms and conversion metrics",
      "AI-powered semantic search and personalization algorithms"
    ],
    bestFor: [
      "Global Enterprise Searches",
      "E-Commerce search analytics",
      "Zero-ops projects",
      "Dynamic Product Recommendations"
    ],
    officialWebsite: "https://www.algolia.com",
    documentationUrl: "https://www.algolia.com/doc/",
    githubUrl: "https://github.com/algolia/algoliasearch-client-javascript",
    relatedTechnologies: ["scout", "nextjs15"],
    experienceLevel: "Advanced",
    difficulty: "Beginner",
    usedInProjects: ["Enterprise Client Portal Search"],
    isCore: false,
    status: "Stable",
    popularity: 92,
    color: "#003DFF"
  },

  // --- INTEGRATIONS ---
  {
    id: "razorpay",
    slug: "razorpay",
    name: "Razorpay",
    fullName: "Razorpay Payment Gateway",
    categoryId: "integrations",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/razorpay.svg",
    iconType: "image",
    creator: "Razorpay",
    releaseYear: 2014,
    description: "The leading payment gateway API suite in India, supporting credit cards, UPI, netbanking, and subscription invoicing.",
    whyWeUseIt: [
      "Industry standard payment success rates and reliable UPI checkouts",
      "Excellent Webhook notifications system to log transaction statuses",
      "Secure by design with fully compliant PCI-DSS frameworks",
      "Automated vendor commission distributions using Razorpay Route"
    ],
    bestFor: [
      "Indian Marketplace Checkouts",
      "UPI payments integrations",
      "SaaS Subscription invoicing",
      "Automated Seller payouts"
    ],
    officialWebsite: "https://razorpay.com",
    documentationUrl: "https://razorpay.com/docs/",
    githubUrl: "https://github.com/razorpay/razorpay-node",
    relatedTechnologies: ["webhooks", "nodejs", "nextjs15"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: ["Multi-Vendor E-Commerce Marketplace"],
    isCore: true,
    status: "Stable",
    popularity: 94,
    color: "#0B72E7"
  },
  {
    id: "pdf-import",
    slug: "pdf-import-pipeline",
    name: "PDF Catalog Import",
    fullName: "PDF Data Parsing & Import Pipeline",
    categoryId: "integrations",
    logo: "file-text",
    iconType: "lucide",
    creator: "Nexora",
    releaseYear: 2022,
    description: "Custom backend parser that extracts metadata and images from supplier PDFs, inserting them into product catalogs.",
    whyWeUseIt: [
      "Eliminates hours of manual data entry for client inventory teams",
      "Accurately extracts text tables using custom PDF stream parsers",
      "Saves images from PDF files, compressing them for web view",
      "Runs asynchronously in backend queues preventing web page timeouts"
    ],
    bestFor: [
      "Supplier inventory bulk loading",
      "Legacy document import pipelines",
      "B2B marketplace catalogs",
      "Document ingestion automation"
    ],
    officialWebsite: "https://nexoralabs.com",
    documentationUrl: "https://nexoralabs.com/docs",
    relatedTechnologies: ["laravel12", "image-pipeline", "bulk-upload"],
    experienceLevel: "Supporting",
    difficulty: "Advanced",
    usedInProjects: ["Multi-Vendor E-Commerce Marketplace"],
    isCore: false,
    status: "Stable",
    popularity: 80,
    color: "#EF4444"
  },
  {
    id: "bulk-upload",
    slug: "bulk-product-upload",
    name: "Bulk Product Upload",
    fullName: "Asynchronous Bulk Product Upload Pipeline",
    categoryId: "integrations",
    logo: "upload-cloud",
    iconType: "lucide",
    creator: "Nexora",
    releaseYear: 2022,
    description: "Robust queue pipeline that processes large CSV/Excel spreadsheets, importing thousands of products with full validation.",
    whyWeUseIt: [
      "Processes 10,000+ items asynchronously without hitting execution limits",
      "Highlights precise row-level syntax errors in visual client dashboards",
      "Performs background checks on duplicates, categories, and image URLs",
      "Greatly simplifies store setup processes for new marketplace sellers"
    ],
    bestFor: [
      "Excel/CSV Seller uploads",
      "Large-scale database importing",
      "Catalog migration pipelines",
      "Batch data correction operations"
    ],
    officialWebsite: "https://nexoralabs.com",
    documentationUrl: "https://nexoralabs.com/docs",
    relatedTechnologies: ["laravel12", "filament", "redis"],
    experienceLevel: "Supporting",
    difficulty: "Advanced",
    usedInProjects: ["Multi-Vendor E-Commerce (Seller Dashboard)"],
    isCore: false,
    status: "Stable",
    popularity: 83,
    color: "#3B82F6"
  },
  {
    id: "image-pipeline",
    slug: "image-processing-pipeline",
    name: "Image Processing Pipelines",
    fullName: "Automated Image Processing & Optimization Pipelines",
    categoryId: "integrations",
    logo: "image",
    iconType: "lucide",
    creator: "Nexora",
    releaseYear: 2021,
    description: "Asynchronous processing service that resizes, compresses, and generates WebP versions of uploaded assets.",
    whyWeUseIt: [
      "Converts bloated PNG/JPG photographs to lightweight modern WebP files",
      "Generates multiple size variations for fast responsive client loading",
      "Runs asynchronously, preventing UI lag during multi-image uploads",
      "Saves valuable storage space and client data transfer bandwidth"
    ],
    bestFor: [
      "E-Commerce Product image processing",
      "User avatar optimization",
      "Dynamic resizing CDNs",
      "SaaS attachments manager"
    ],
    officialWebsite: "https://nexoralabs.com",
    documentationUrl: "https://nexoralabs.com/docs",
    relatedTechnologies: ["nodejs", "laravel12", "build-opt"],
    experienceLevel: "Supporting",
    difficulty: "Intermediate",
    usedInProjects: ["Multi-Vendor E-Commerce", "SaaS Platform UI", "Nexora Website Assets"],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#10B981"
  },
  {
    id: "filament",
    slug: "filament-admin",
    name: "Admin Panel Automation (Filament)",
    fullName: "Filament PHP Admin Panel Framework",
    categoryId: "integrations",
    logo: "layout-template",
    iconType: "lucide",
    creator: "Dan Harrin",
    releaseYear: 2020,
    description: "A collection of beautiful full-stack components for Laravel, enabling immediate generation of administrative dashboards.",
    whyWeUseIt: [
      "Cuts down backend CRUD dashboard development time by 75%",
      "Provides responsive, pre-designed forms, tables, and metric widgets",
      "Built-in integrations for file uploads, exports, and security permissions",
      "Built entirely on top of Livewire and Tailwind CSS"
    ],
    bestFor: [
      "Laravel Back-Office Panels",
      "Customer Relation Dashboards",
      "E-Commerce Seller Portals",
      "Rapid Prototype database managers"
    ],
    officialWebsite: "https://filamentphp.com",
    documentationUrl: "https://filamentphp.com/docs",
    githubUrl: "https://github.com/filamentphp/filament",
    relatedTechnologies: ["laravel12", "livewire", "tailwindcss"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["Multi-Vendor E-Commerce Admin", "FinTech back-office hub"],
    isCore: true,
    status: "Stable",
    popularity: 90,
    color: "#F59E0B"
  },

  // --- UI LIBRARIES ---
  {
    id: "shadcn",
    slug: "shadcn-ui",
    name: "shadcn/ui",
    fullName: "shadcn/ui Component Collection",
    categoryId: "ui-libraries",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/shadcnui.svg",
    iconType: "image",
    creator: "Shadcn",
    releaseYear: 2023,
    description: "Beautifully designed UI components that you copy and paste into your apps, built using Radix UI and Tailwind CSS.",
    whyWeUseIt: [
      "You own the code—no locked-in NPM package updates to break layouts",
      "Highly accessible out of the box following strict ARIA guidelines",
      "Fully styled with Tailwind CSS, making overrides effortless",
      "Keeps codebase footprint lightweight, importing only what you need"
    ],
    bestFor: [
      "Modern SaaS Frontends",
      "Consistent Design Systems",
      "Accessible Web Interfaces",
      "Next.js Dashboard layouts"
    ],
    officialWebsite: "https://ui.shadcn.com",
    documentationUrl: "https://ui.shadcn.com/docs",
    githubUrl: "https://github.com/shadcn-ui/ui",
    relatedTechnologies: ["radix", "tailwindcss", "react19"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform", "Nexora Website", "Client Portal Frontends"],
    isCore: true,
    status: "Stable",
    popularity: 96,
    color: "#000000"
  },
  {
    id: "radix",
    slug: "radix-ui",
    name: "Radix UI",
    fullName: "Radix UI Primitives",
    categoryId: "ui-libraries",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/radixui.svg",
    iconType: "image",
    creator: "WorkOS",
    releaseYear: 2020,
    description: "An open-source UI component library for building high-quality, accessible design systems and web apps.",
    whyWeUseIt: [
      "Focuses entirely on accessibility (WAI-ARIA) and keyboard navigation",
      "Completely unstyled primitives, giving full visual design freedom",
      "Handles complex interactions (modals, dropdowns, tooltips) seamlessly",
      "The underlying architecture powering shadcn/ui components"
    ],
    bestFor: [
      "Accessibility-Critical Web Apps",
      "Custom Design Systems",
      "Interactive popovers & dropdowns",
      "Unstyled React Primitives"
    ],
    officialWebsite: "https://www.radix-ui.com",
    documentationUrl: "https://www.radix-ui.com/primitives/docs/overview/introduction",
    githubUrl: "https://github.com/radix-ui/primitives",
    relatedTechnologies: ["shadcn", "react19"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: ["SaaS Platform", "Nexora Website", "Customer portal menus"],
    isCore: false,
    status: "Stable",
    popularity: 91,
    color: "#161618"
  },
  {
    id: "lucide-react",
    slug: "lucide-icons",
    name: "Lucide React",
    fullName: "Lucide Icon Suite",
    categoryId: "ui-libraries",
    logo: "palette",
    iconType: "lucide",
    creator: "Lucide",
    releaseYear: 2020,
    description: "A community-run fork of Feather Icons, offering thousands of clean, customizable vector SVG icons for web interfaces.",
    whyWeUseIt: [
      "Extremely clean, modern, consistent stroke weight aesthetics",
      "Includes thousands of vector icons for diverse features",
      "Supports tree-shaking—keeps bundles small by importing specific icons",
      "Easy adjustments for stroke width, size, and coloring inline"
    ],
    bestFor: [
      "Modern Web App Icons",
      "Dashboard Navigation menus",
      "Interface indicators",
      "Action buttons markup"
    ],
    officialWebsite: "https://lucide.dev",
    documentationUrl: "https://lucide.dev/docs/lucide-react/guide",
    githubUrl: "https://github.com/lucide-icons/lucide",
    relatedTechnologies: ["react19", "shadcn", "tailwindcss"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["SaaS Platform", "Multi-Vendor E-Commerce", "Nexora Website"],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#F43F5E"
  },
  {
    id: "framer",
    slug: "framer-motion",
    name: "Framer Motion",
    fullName: "Framer Motion Animation Engine",
    categoryId: "ui-libraries",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/framer.svg",
    iconType: "image",
    creator: "Framer",
    releaseYear: 2018,
    description: "A popular, production-ready motion and animation library for React web applications.",
    whyWeUseIt: [
      "Declarative animation syntax makes complex page transitions simple",
      "Exceptional layout-animations engine that morphs sizes automatically",
      "Robust support for gestural inputs (hover, drag, tap, scroll)",
      "AnimatePresence component permits animating elements as they unmount"
    ],
    bestFor: [
      "Premium landing pages",
      "Smooth layout transitions",
      "Gesture-driven interfaces",
      "Interactive page guides"
    ],
    officialWebsite: "https://motion.dev/",
    documentationUrl: "https://motion.dev/docs",
    githubUrl: "https://github.com/motiondivision/motion",
    relatedTechnologies: ["react19", "nextjs15", "tailwindcss"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: ["Nexora Website (All Animations)", "Interactive Landing Pages"],
    isCore: false,
    status: "Stable",
    popularity: 93,
    color: "#0055FF"
  },

  // --- TOOLS ---
  {
    id: "git",
    slug: "git",
    name: "Git",
    fullName: "Git Distributed Version Control",
    categoryId: "tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/git.svg",
    iconType: "image",
    creator: "Linus Torvalds",
    releaseYear: 2005,
    description: "A fast, distributed version control system designed to handle everything from small to very large projects with speed and efficiency.",
    whyWeUseIt: [
      "Industry standard code versioning and branch management",
      "Enables clean collaborative workflows (Pull Requests, code reviews)",
      "Allows easy tracking of code mutations and fast rollbacks",
      "Integrates with all CI/CD deployment pipelines"
    ],
    bestFor: [
      "Code Version Control",
      "Team Collaborations",
      "Audit Trail logging",
      "CI/CD release triggers"
    ],
    officialWebsite: "https://git-scm.com",
    documentationUrl: "https://git-scm.com/doc",
    githubUrl: "https://github.com/git/git",
    relatedTechnologies: ["github", "vscode"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["All Nexora Repositories", "All Client projects"],
    isCore: true,
    status: "Stable",
    popularity: 100,
    color: "#F05032"
  },
  {
    id: "github",
    slug: "github",
    name: "GitHub",
    fullName: "GitHub Repository Hosting",
    categoryId: "tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/github.svg",
    iconType: "image",
    creator: "Microsoft",
    releaseYear: 2008,
    description: "A cloud-based hosting service for Git repositories, offering pull requests, issue trackers, actions, and projects management.",
    whyWeUseIt: [
      "Centralized hub for all development repository codes",
      "Powerful automation actions (GitHub Actions) for CI/CD",
      "Outstanding code review and team coordination tools",
      "Native integrations with Slack, Vercel, and project trackers"
    ],
    bestFor: [
      "Remote Repository Hosting",
      "Continuous Integration Pipelines",
      "Pull Request reviews",
      "Project Roadmap tracking"
    ],
    officialWebsite: "https://github.com",
    documentationUrl: "https://docs.github.com",
    relatedTechnologies: ["git", "vscode", "vercel"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["All Nexora Projects", "Client code handovers"],
    isCore: true,
    status: "Stable",
    popularity: 99,
    color: "#181717"
  },
  {
    id: "postman",
    slug: "postman",
    name: "Postman",
    fullName: "Postman API Platform",
    categoryId: "tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/postman.svg",
    iconType: "image",
    creator: "Postman Inc.",
    releaseYear: 2012,
    description: "An API platform for building and using APIs, simplifying each step of the API lifecycle and streamlining collaboration.",
    whyWeUseIt: [
      "Speeds up API endpoint testing without frontends ready",
      "Enables sharing of request collections across the engineering team",
      "Supports automated API response tests validation",
      "Generates API documentation drafts automatically"
    ],
    bestFor: [
      "API Testing & Diagnostics",
      "Team Request Collections",
      "Mock API server creation",
      "Load testing endpoints"
    ],
    officialWebsite: "https://www.postman.com",
    documentationUrl: "https://learning.postman.com/docs/publishing-your-api/documenting-your-api/",
    relatedTechnologies: ["rest-apis", "expressjs", "laravel12"],
    experienceLevel: "Advanced",
    difficulty: "Beginner",
    usedInProjects: ["SaaS API Testing", "FinTech integration testing"],
    isCore: false,
    status: "Stable",
    popularity: 93,
    color: "#FF6C37"
  },
  {
    id: "vscode",
    slug: "vscode",
    name: "VS Code",
    fullName: "Visual Studio Code Editor",
    categoryId: "tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/visualstudiocode.svg",
    iconType: "image",
    creator: "Microsoft",
    releaseYear: 2015,
    description: "A lightweight, powerful source code editor that runs on your desktop, featuring rich support for extensions.",
    whyWeUseIt: [
      "Extremely fast editor startup and light memory footprints",
      "Infinite extension marketplace for linting, autocompleting, and databases",
      "Outstanding integrated git viewer and terminal panel",
      "Primary code editor of choice across the Nexora team"
    ],
    bestFor: [
      "Daily Software Development",
      "Multi-Language coding",
      "Git diff reviews",
      "Integrated terminal scripting"
    ],
    officialWebsite: "https://code.visualstudio.com",
    documentationUrl: "https://code.visualstudio.com/docs",
    githubUrl: "https://github.com/microsoft/vscode",
    relatedTechnologies: ["git", "github"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: ["Daily Coding Projects", "Frontend/Backend setups"],
    isCore: true,
    status: "Stable",
    popularity: 98,
    color: "#007ACC"
  },
  {
    id: "android-studio",
    slug: "android-studio",
    name: "Android Studio",
    fullName: "Android Studio IDE",
    categoryId: "tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/androidstudio.svg",
    iconType: "image",
    creator: "Google",
    releaseYear: 2013,
    description: "The official Integrated Development Environment (IDE) for Google's Android operating system, built on JetBrains' IntelliJ IDEA.",
    whyWeUseIt: [
      "De-facto tool for compiling, testing, and release-signing Android apps",
      "Includes highly accurate system emulators for testing UI layouts",
      "Advanced memory profiling and CPU telemetry logs analyzers",
      "Seamless integration with Kotlin and Firebase SDK packages"
    ],
    bestFor: [
      "Android App Compilations",
      "Device Emulator testing",
      "Mobile APK/AAB builds",
      "Gradle dependencies manager"
    ],
    officialWebsite: "https://developer.android.com/studio",
    documentationUrl: "https://developer.android.com/studio/intro",
    relatedTechnologies: ["firebase", "git"],
    experienceLevel: "Supporting",
    difficulty: "Advanced",
    usedInProjects: ["FinTech Mobile App release builds"],
    isCore: false,
    status: "Stable",
    popularity: 84,
    color: "#3DDC84"
  },
  {
    id: "vite",
    slug: "vite",
    name: "Vite",
    fullName: "Vite Build Tool",
    categoryId: "tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/vite.svg",
    iconType: "image",
    creator: "Evan You",
    releaseYear: 2020,
    description: "A modern, ultra-fast frontend build tool that leverages native ES modules and esbuild for rapid development and building.",
    whyWeUseIt: [
      "Instant server start times and hot module replacement (HMR)",
      "Highly optimized Rollup build engine for production assets",
      "Zero-config support for TypeScript, JSX, and CSS preprocessors",
      "Default build system wrapper in Laravel 12 and React client applications"
    ],
    bestFor: [
      "Fast local dev servers",
      "React Client builds",
      "Tailwind compilation integration",
      "Asset bundling pipelines"
    ],
    officialWebsite: "https://vite.dev",
    documentationUrl: "https://vite.dev/guide/",
    githubUrl: "https://github.com/vitejs/vite",
    relatedTechnologies: ["react19", "tailwindcss", "laravel12"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: ["Multi-Vendor E-Commerce (Client Dev)", "Laravel Admin dashboards", "Nexora Landing Pages"],
    isCore: true,
    status: "Stable",
    popularity: 94,
    color: "#646CFF"
  }
];
