import { Technology } from "@/types";

export const technologies: Technology[] = [
  // Frontend
  {
    id: "nextjs",
    slug: "nextjs",
    name: "Next.js",
    fullName: "Next.js React Framework",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/nextdotjs.svg",
    iconType: "image",
    creator: "Vercel",
    releaseYear: 2016,
    description: "The React framework for production with hybrid static & server rendering.",
    whyWeUseIt: ["Server-side rendering", "Static site generation", "App Router architecture", "Automatic image optimization"],
    bestFor: ["SaaS applications", "Marketing websites", "E-commerce platforms"],
    officialWebsite: "https://nextjs.org",
    documentationUrl: "https://nextjs.org/docs",
    githubUrl: "https://github.com/vercel/next.js",
    relatedTechnologies: ["react", "typescript", "tailwindcss"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 98,
    color: "#000000",
  },
  {
    id: "react",
    slug: "react",
    name: "React",
    fullName: "React UI Library",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/react.svg",
    iconType: "image",
    creator: "Meta",
    releaseYear: 2013,
    description: "A JavaScript library for building user interfaces.",
    whyWeUseIt: ["Component-based architecture", "Virtual DOM", "Rich ecosystem", "Cross-platform support"],
    bestFor: ["Single-page applications", "Interactive dashboards", "Progressive web apps"],
    officialWebsite: "https://react.dev",
    documentationUrl: "https://react.dev/reference/react",
    githubUrl: "https://github.com/facebook/react",
    relatedTechnologies: ["nextjs", "typescript", "react-native"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 99,
    color: "#61DAFB",
  },
  {
    id: "typescript",
    slug: "typescript",
    name: "TypeScript",
    fullName: "TypeScript Programming Language",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/typescript.svg",
    iconType: "image",
    creator: "Microsoft",
    releaseYear: 2012,
    description: "A strongly typed programming language that builds on JavaScript.",
    whyWeUseIt: ["Static type checking", "Better IDE support", "Easier refactoring", "Catch errors early"],
    bestFor: ["Large-scale applications", "Team collaboration", "Maintainable codebases"],
    officialWebsite: "https://www.typescriptlang.org",
    documentationUrl: "https://www.typescriptlang.org/docs/",
    githubUrl: "https://github.com/microsoft/TypeScript",
    relatedTechnologies: ["react", "nextjs", "nodejs"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 97,
    color: "#3178C6",
  },
  {
    id: "tailwindcss",
    slug: "tailwindcss",
    name: "Tailwind CSS",
    fullName: "Tailwind CSS Framework",
    categoryId: "frontend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tailwindcss.svg",
    iconType: "image",
    creator: "Tailwind Labs",
    releaseYear: 2017,
    description: "A utility-first CSS framework for rapidly building custom user interfaces.",
    whyWeUseIt: ["Rapid UI development", "Consistent design system", "Small production bundle size", "Responsive design"],
    bestFor: ["Rapid prototyping", "Design systems", "Responsive applications"],
    officialWebsite: "https://tailwindcss.com",
    documentationUrl: "https://tailwindcss.com/docs",
    githubUrl: "https://github.com/tailwindlabs/tailwindcss",
    relatedTechnologies: ["nextjs", "react"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#06B6D4",
  },

  // Backend
  {
    id: "laravel",
    slug: "laravel",
    name: "Laravel",
    fullName: "Laravel PHP Framework",
    categoryId: "backend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/laravel.svg",
    iconType: "image",
    creator: "Taylor Otwell",
    releaseYear: 2011,
    description: "The PHP framework for web artisans.",
    whyWeUseIt: ["Eloquent ORM", "Blade templating", "Built-in authentication", "Queue system"],
    bestFor: ["Web applications", "APIs", "E-commerce platforms"],
    officialWebsite: "https://laravel.com",
    documentationUrl: "https://laravel.com/docs",
    githubUrl: "https://github.com/laravel/laravel",
    relatedTechnologies: ["php", "postgresql", "redis"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 94,
    color: "#FF2D20",
  },
  {
    id: "php",
    slug: "php",
    name: "PHP",
    fullName: "PHP Hypertext Preprocessor",
    categoryId: "backend",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/php.svg",
    iconType: "image",
    creator: "Rasmus Lerdorf",
    releaseYear: 1995,
    description: "A popular general-purpose scripting language especially suited to web development.",
    whyWeUseIt: ["Fast execution", "Large ecosystem", "Great for Laravel", "Easy to deploy"],
    bestFor: ["Server-side logic", "Web APIs", "Dynamic websites"],
    officialWebsite: "https://www.php.net",
    documentationUrl: "https://www.php.net/docs.php",
    githubUrl: "https://github.com/php/php-src",
    relatedTechnologies: ["laravel", "apache", "postgresql"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 90,
    color: "#777BB4",
  },
  {
    id: "rest-apis",
    slug: "rest-apis",
    name: "REST APIs",
    fullName: "REST API Architecture",
    categoryId: "backend",
    logo: "Globe",
    iconType: "lucide",
    creator: "Roy Fielding",
    releaseYear: 2000,
    description: "Architectural style for designing networked applications.",
    whyWeUseIt: ["Stateless", "Scalable", "Easy to cache", "Widely adopted"],
    bestFor: ["Public APIs", "Mobile app backends", "Microservices"],
    officialWebsite: "https://restfulapi.net",
    documentationUrl: "https://restfulapi.net",
    githubUrl: "",
    relatedTechnologies: ["laravel", "nodejs"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 99,
    color: "#0F172A",
  },
  {
    id: "authentication",
    slug: "authentication",
    name: "Authentication",
    fullName: "Authentication & Authorization",
    categoryId: "backend",
    logo: "Lock",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Security protocols for verifying user identity and access control.",
    whyWeUseIt: ["Secure user sessions", "Role-based access control", "OAuth integration", "Password security"],
    bestFor: ["User management", "Secure APIs", "Multi-tenant apps"],
    officialWebsite: "https://oauth.net",
    documentationUrl: "https://oauth.net",
    githubUrl: "",
    relatedTechnologies: ["laravel", "supabase"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 96,
    color: "#1E293B",
  },

  // Mobile
  {
    id: "flutter",
    slug: "flutter",
    name: "Flutter",
    fullName: "Flutter UI Toolkit",
    categoryId: "mobile",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/flutter.svg",
    iconType: "image",
    creator: "Google",
    releaseYear: 2017,
    description: "UI toolkit for building natively compiled applications for mobile, web, and desktop from a single codebase.",
    whyWeUseIt: ["Single codebase", "Native performance", "Rich widgets", "Hot reload"],
    bestFor: ["Cross-platform apps", "Mobile applications", "Custom UI designs"],
    officialWebsite: "https://flutter.dev",
    documentationUrl: "https://flutter.dev/docs",
    githubUrl: "https://github.com/flutter/flutter",
    relatedTechnologies: ["dart"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 93,
    color: "#02569B",
  },
  {
    id: "react-native",
    slug: "react-native",
    name: "React Native",
    fullName: "React Native Mobile Framework",
    categoryId: "mobile",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/react.svg",
    iconType: "image",
    creator: "Meta",
    releaseYear: 2015,
    description: "A framework for building native apps using React.",
    whyWeUseIt: ["Reuse React knowledge", "Native components", "Large community", "Expo ecosystem"],
    bestFor: ["Mobile apps", "Cross-platform development", "React-based teams"],
    officialWebsite: "https://reactnative.dev",
    documentationUrl: "https://reactnative.dev/docs",
    githubUrl: "https://github.com/facebook/react-native",
    relatedTechnologies: ["react", "typescript", "expo"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 92,
    color: "#61DAFB",
  },

  // Database
  {
    id: "postgresql",
    slug: "postgresql",
    name: "PostgreSQL",
    fullName: "PostgreSQL Relational Database",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/postgresql.svg",
    iconType: "image",
    creator: "PostgreSQL Global Development Group",
    releaseYear: 1996,
    description: "A powerful, open source object-relational database system.",
    whyWeUseIt: ["ACID compliance", "JSONB support", "Advanced queries", "Extensible"],
    bestFor: ["Complex applications", "Data analytics", "Enterprise systems"],
    officialWebsite: "https://www.postgresql.org",
    documentationUrl: "https://www.postgresql.org/docs/",
    githubUrl: "https://github.com/postgres/postgres",
    relatedTechnologies: ["supabase", "laravel", "redis"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#4169E1",
  },
  {
    id: "supabase",
    slug: "supabase",
    name: "Supabase",
    fullName: "Supabase Backend-as-a-Service",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/supabase.svg",
    iconType: "image",
    creator: "Supabase",
    releaseYear: 2020,
    description: "The open source Firebase alternative.",
    whyWeUseIt: ["PostgreSQL database", "Instant APIs", "Auth built-in", "Realtime subscriptions"],
    bestFor: ["Rapid MVPs", "Real-time apps", "Serverless backends"],
    officialWebsite: "https://supabase.com",
    documentationUrl: "https://supabase.com/docs",
    githubUrl: "https://github.com/supabase/supabase",
    relatedTechnologies: ["postgresql", "nextjs", "authentication"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 94,
    color: "#3ECF8E",
  },
  {
    id: "redis",
    slug: "redis",
    name: "Redis",
    fullName: "Redis In-Memory Data Store",
    categoryId: "database",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/redis.svg",
    iconType: "image",
    creator: "Salvatore Sanfilippo",
    releaseYear: 2009,
    description: "Open source, in-memory data structure store, used as a database, cache, and message broker.",
    whyWeUseIt: ["Ultra-fast", "Caching", "Session storage", "Pub/Sub"],
    bestFor: ["Caching layer", "Session management", "Real-time features"],
    officialWebsite: "https://redis.io",
    documentationUrl: "https://redis.io/documentation",
    githubUrl: "https://github.com/redis/redis",
    relatedTechnologies: ["laravel", "postgresql", "docker"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 93,
    color: "#DC382D",
  },

  // Infrastructure
  {
    id: "docker",
    slug: "docker",
    name: "Docker",
    fullName: "Docker Containerization",
    categoryId: "infrastructure",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/docker.svg",
    iconType: "image",
    creator: "Docker Inc.",
    releaseYear: 2013,
    description: "Platform for developing, shipping, and running applications in containers.",
    whyWeUseIt: ["Consistent environments", "Isolation", "Portable", "Easy scaling"],
    bestFor: ["Local development", "Microservices", "CI/CD pipelines"],
    officialWebsite: "https://www.docker.com",
    documentationUrl: "https://docs.docker.com",
    githubUrl: "https://github.com/docker/docker-ce",
    relatedTechnologies: ["docker-compose", "render"],
    experienceLevel: "Primary",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 97,
    color: "#2496ED",
  },
  {
    id: "docker-compose",
    slug: "docker-compose",
    name: "Docker Compose",
    fullName: "Docker Compose Orchestration",
    categoryId: "infrastructure",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/docker.svg",
    iconType: "image",
    creator: "Docker Inc.",
    releaseYear: 2014,
    description: "Define and run multi-container Docker applications.",
    whyWeUseIt: ["Local multi-container setups", "Simple orchestration", "Environment consistency"],
    bestFor: ["Local development", "Multi-service apps", "Testing environments"],
    officialWebsite: "https://docs.docker.com/compose/",
    documentationUrl: "https://docs.docker.com/compose/",
    githubUrl: "https://github.com/docker/compose",
    relatedTechnologies: ["docker"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 95,
    color: "#2496ED",
  },
  {
    id: "wsl2",
    slug: "wsl2",
    name: "WSL2",
    fullName: "Windows Subsystem for Linux 2",
    categoryId: "infrastructure",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/windows.svg",
    iconType: "image",
    creator: "Microsoft",
    releaseYear: 2019,
    description: "Compatibility layer for running Linux binary executables natively on Windows.",
    whyWeUseIt: ["Linux environment on Windows", "Docker integration", "Better performance"],
    bestFor: ["Windows development", "Linux tooling", "Docker Desktop"],
    officialWebsite: "https://learn.microsoft.com/en-us/windows/wsl/",
    documentationUrl: "https://learn.microsoft.com/en-us/windows/wsl/",
    githubUrl: "https://github.com/microsoft/WSL",
    relatedTechnologies: ["docker", "windows"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#0078D4",
  },
  {
    id: "apache",
    slug: "apache",
    name: "Apache",
    fullName: "Apache HTTP Server",
    categoryId: "infrastructure",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/apache.svg",
    iconType: "image",
    creator: "Apache Software Foundation",
    releaseYear: 1995,
    description: "A free and open-source cross-platform web server software.",
    whyWeUseIt: ["Proven reliability", ".htaccess support", "Modular", "Widely hosted"],
    bestFor: ["PHP applications", "Static hosting", "Legacy systems"],
    officialWebsite: "https://httpd.apache.org",
    documentationUrl: "https://httpd.apache.org/docs/",
    githubUrl: "https://github.com/apache/httpd",
    relatedTechnologies: ["php", "laravel"],
    experienceLevel: "Supporting",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#D22128",
  },

  // Deployment
  {
    id: "render",
    slug: "render",
    name: "Render",
    fullName: "Render Cloud Platform",
    categoryId: "deployment",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/render.svg",
    iconType: "image",
    creator: "Render",
    releaseYear: 2019,
    description: "A cloud platform that makes it easy to build and run apps and websites.",
    whyWeUseIt: ["Zero-config deployments", "Git integration", "Managed databases", "SSL by default"],
    bestFor: ["Web apps", "APIs", "Static sites"],
    officialWebsite: "https://render.com",
    documentationUrl: "https://docs.render.com",
    githubUrl: "",
    relatedTechnologies: ["docker", "github", "postgresql"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 85,
    color: "#46E3B7",
  },
  {
    id: "github",
    slug: "github",
    name: "GitHub",
    fullName: "GitHub Development Platform",
    categoryId: "deployment",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/github.svg",
    iconType: "image",
    creator: "Tom Preston-Werner",
    releaseYear: 2008,
    description: "A provider of Internet hosting for software development and version control using Git.",
    whyWeUseIt: ["Version control", "Collaboration", "GitHub Actions", "Pull requests"],
    bestFor: ["Code hosting", "Team collaboration", "Open source"],
    officialWebsite: "https://github.com",
    documentationUrl: "https://docs.github.com",
    githubUrl: "https://github.com/github",
    relatedTechnologies: ["git", "github-actions", "render"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 100,
    color: "#181717",
  },
  {
    id: "cicd",
    slug: "cicd",
    name: "CI/CD",
    fullName: "Continuous Integration & Continuous Deployment",
    categoryId: "deployment",
    logo: "Zap",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Practice of automating the build, test, and deployment processes.",
    whyWeUseIt: ["Faster releases", "Less bugs", "Automated testing", "Consistent deployments"],
    bestFor: ["Agile teams", "Frequent deployments", "Quality assurance"],
    officialWebsite: "https://www.atlassian.com/continuous-delivery",
    documentationUrl: "https://www.atlassian.com/continuous-delivery",
    githubUrl: "",
    relatedTechnologies: ["github", "github-actions", "render"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 96,
    color: "#2563EB",
  },
  {
    id: "environment-management",
    slug: "environment-management",
    name: "Environment Management",
    fullName: "Environment Configuration Management",
    categoryId: "deployment",
    logo: "Settings",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Managing different environments (development, staging, production).",
    whyWeUseIt: ["Isolate environments", "Prevent config leaks", "Consistent builds"],
    bestFor: ["Multi-environment apps", "Secure configurations", "Dev/prod parity"],
    officialWebsite: "https://12factor.net/config",
    documentationUrl: "https://12factor.net/config",
    githubUrl: "",
    relatedTechnologies: ["docker", "github", "render"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 90,
    color: "#64748B",
  },
  {
    id: "build-optimization",
    slug: "build-optimization",
    name: "Build Optimization",
    fullName: "Build & Asset Optimization",
    categoryId: "deployment",
    logo: "Zap",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2015,
    description: "Techniques to optimize build times and asset sizes.",
    whyWeUseIt: ["Faster builds", "Smaller bundles", "Better performance"],
    bestFor: ["Large applications", "Performance-critical apps", "CI/CD pipelines"],
    officialWebsite: "https://web.dev/fast/",
    documentationUrl: "https://web.dev/fast/",
    githubUrl: "",
    relatedTechnologies: ["nextjs", "tailwindcss", "typescript"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 87,
    color: "#16A34A",
  },

  // AI
  {
    id: "openai",
    slug: "openai",
    name: "OpenAI",
    fullName: "OpenAI API",
    categoryId: "ai",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/openai.svg",
    iconType: "image",
    creator: "OpenAI",
    releaseYear: 2020,
    description: "API for accessing powerful AI models like GPT.",
    whyWeUseIt: ["Powerful language models", "Easy to integrate", "Good documentation"],
    bestFor: ["Chatbots", "Content generation", "AI features"],
    officialWebsite: "https://openai.com",
    documentationUrl: "https://platform.openai.com/docs",
    githubUrl: "",
    relatedTechnologies: ["google-gemini", "nextjs"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 99,
    color: "#412991",
  },
  {
    id: "google-gemini",
    slug: "google-gemini",
    name: "Google Gemini",
    fullName: "Google Gemini API",
    categoryId: "ai",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/google.svg",
    iconType: "image",
    creator: "Google",
    releaseYear: 2023,
    description: "Google's AI model for text, images, and more.",
    whyWeUseIt: ["Multimodal", "Google ecosystem", "Good performance"],
    bestFor: ["AI features", "Multimodal apps", "Chatbots"],
    officialWebsite: "https://ai.google.dev",
    documentationUrl: "https://ai.google.dev/docs",
    githubUrl: "",
    relatedTechnologies: ["openai", "nextjs"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#4285F4",
  },
  {
    id: "business-automation",
    slug: "business-automation",
    name: "Business Automation",
    fullName: "Business Process Automation",
    categoryId: "ai",
    logo: "Workflow",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2010,
    description: "Automating repetitive business processes using AI and code.",
    whyWeUseIt: ["Save time", "Reduce errors", "Scale operations"],
    bestFor: ["Workflow automation", "Data processing", "Customer support"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["openai", "laravel", "nodejs"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#8B5CF6",
  },

  // Development Tools
  {
    id: "git",
    slug: "git",
    name: "Git",
    fullName: "Git Version Control",
    categoryId: "development-tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/git.svg",
    iconType: "image",
    creator: "Linus Torvalds",
    releaseYear: 2005,
    description: "Distributed version control system designed to handle everything from small to very large projects.",
    whyWeUseIt: ["Distributed", "Branching", "History tracking", "Collaboration"],
    bestFor: ["Version control", "Team collaboration", "Code management"],
    officialWebsite: "https://git-scm.com",
    documentationUrl: "https://git-scm.com/doc",
    githubUrl: "https://github.com/git/git",
    relatedTechnologies: ["github", "vscode"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 100,
    color: "#F05032",
  },
  {
    id: "composer",
    slug: "composer",
    name: "Composer",
    fullName: "Composer PHP Package Manager",
    categoryId: "development-tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/composer.svg",
    iconType: "image",
    creator: "Nils Adermann & Jordi Boggiano",
    releaseYear: 2011,
    description: "Dependency Manager for PHP.",
    whyWeUseIt: ["Package management", "Autoloading", "Version constraints"],
    bestFor: ["PHP applications", "Laravel projects", "Dependency management"],
    officialWebsite: "https://getcomposer.org",
    documentationUrl: "https://getcomposer.org/doc/",
    githubUrl: "https://github.com/composer/composer",
    relatedTechnologies: ["php", "laravel"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 92,
    color: "#885630",
  },
  {
    id: "postman",
    slug: "postman",
    name: "Postman",
    fullName: "Postman API Platform",
    categoryId: "development-tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/postman.svg",
    iconType: "image",
    creator: "Postman Inc.",
    releaseYear: 2014,
    description: "API platform for building and using APIs.",
    whyWeUseIt: ["API testing", "Documentation", "Collections", "Environments"],
    bestFor: ["API development", "Testing endpoints", "Collaboration"],
    officialWebsite: "https://www.postman.com",
    documentationUrl: "https://learning.postman.com/docs",
    githubUrl: "",
    relatedTechnologies: ["rest-apis", "laravel", "nodejs"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 94,
    color: "#FF6C37",
  },
  {
    id: "vscode",
    slug: "vscode",
    name: "VS Code",
    fullName: "Visual Studio Code",
    categoryId: "development-tools",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/visualstudiocode.svg",
    iconType: "image",
    creator: "Microsoft",
    releaseYear: 2015,
    description: "A lightweight but powerful source code editor.",
    whyWeUseIt: ["Extensions", "Git integration", "Debugging", "Great TypeScript support"],
    bestFor: ["Code editing", "Debugging", "All development"],
    officialWebsite: "https://code.visualstudio.com",
    documentationUrl: "https://code.visualstudio.com/docs",
    githubUrl: "https://github.com/microsoft/vscode",
    relatedTechnologies: ["typescript", "git", "debugging"],
    experienceLevel: "Core",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 98,
    color: "#007ACC",
  },
  {
    id: "debugging",
    slug: "debugging",
    name: "Debugging",
    fullName: "Debugging & Troubleshooting",
    categoryId: "development-tools",
    logo: "Bug",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Process of finding and fixing bugs in code.",
    whyWeUseIt: ["Fix issues", "Improve quality", "Root cause analysis"],
    bestFor: ["All development", "Production issues", "Quality assurance"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["vscode", "logging", "production-debugging"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 95,
    color: "#DC2626",
  },
  {
    id: "logging",
    slug: "logging",
    name: "Logging",
    fullName: "Application Logging & Monitoring",
    categoryId: "development-tools",
    logo: "Activity",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Recording events and activities in applications.",
    whyWeUseIt: ["Track issues", "Monitor performance", "Audit trails"],
    bestFor: ["Production monitoring", "Debugging", "Analytics"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["laravel", "nodejs", "debugging"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 90,
    color: "#2563EB",
  },
  {
    id: "devtools-performance-optimization",
    slug: "devtools-performance-optimization",
    name: "Performance Optimization",
    fullName: "Performance Optimization Techniques",
    categoryId: "development-tools",
    logo: "Gauge",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2010,
    description: "Techniques to optimize application performance.",
    whyWeUseIt: ["Faster apps", "Better UX", "Lower costs"],
    bestFor: ["High-traffic apps", "Performance-critical apps", "Mobile apps"],
    officialWebsite: "https://web.dev/fast/",
    documentationUrl: "https://web.dev/fast/",
    githubUrl: "",
    relatedTechnologies: ["nextjs", "laravel", "redis"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#16A34A",
  },

  // Search
  {
    id: "laravel-scout",
    slug: "laravel-scout",
    name: "Laravel Scout",
    fullName: "Laravel Scout Search",
    categoryId: "search",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/laravel.svg",
    iconType: "image",
    creator: "Taylor Otwell",
    releaseYear: 2016,
    description: "Driver based full-text search for Laravel Eloquent models.",
    whyWeUseIt: ["Easy integration", "Eloquent-friendly", "Multiple drivers"],
    bestFor: ["Search in Laravel apps", "Full-text search"],
    officialWebsite: "https://laravel.com/docs/scout",
    documentationUrl: "https://laravel.com/docs/scout",
    githubUrl: "https://github.com/laravel/scout",
    relatedTechnologies: ["laravel", "algolia", "meilisearch"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#FF2D20",
  },

  // Storage
  {
    id: "laravel-storage",
    slug: "laravel-storage",
    name: "Laravel Storage",
    fullName: "Laravel File Storage",
    categoryId: "storage",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/laravel.svg",
    iconType: "image",
    creator: "Taylor Otwell",
    releaseYear: 2011,
    description: "Laravel's filesystem abstraction for file storage.",
    whyWeUseIt: ["Multiple drivers", "Easy to use", "Secure"],
    bestFor: ["File uploads", "Storage management", "Laravel apps"],
    officialWebsite: "https://laravel.com/docs/filesystem",
    documentationUrl: "https://laravel.com/docs/filesystem",
    githubUrl: "https://github.com/laravel/framework",
    relatedTechnologies: ["laravel", "s3"],
    experienceLevel: "Supporting",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#FF2D20",
  },
  {
    id: "image-upload-pipeline",
    slug: "image-upload-pipeline",
    name: "Image Upload Pipeline",
    fullName: "Image Upload & Processing Pipeline",
    categoryId: "storage",
    logo: "Image",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2015,
    description: "Pipeline for uploading, processing, and serving images.",
    whyWeUseIt: ["Optimize images", "CDN integration", "Resize on upload"],
    bestFor: ["E-commerce", "Social apps", "Media platforms"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["laravel-storage", "s3", "nextjs"],
    experienceLevel: "Supporting",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#3B82F6",
  },

  // Payments
  {
    id: "razorpay",
    slug: "razorpay",
    name: "Razorpay",
    fullName: "Razorpay Payment Gateway",
    categoryId: "payments",
    logo: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/razorpay.svg",
    iconType: "image",
    creator: "Razorpay",
    releaseYear: 2014,
    description: "India's leading payment gateway.",
    whyWeUseIt: ["Easy integration", "Multiple payment methods", "Good documentation"],
    bestFor: ["Indian businesses", "E-commerce", "Subscriptions"],
    officialWebsite: "https://razorpay.com",
    documentationUrl: "https://razorpay.com/docs/",
    githubUrl: "https://github.com/razorpay",
    relatedTechnologies: ["laravel", "nodejs", "nextjs"],
    experienceLevel: "Primary",
    difficulty: "Beginner",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 80,
    color: "#0C2E86",
  },

  // Engineering Practices
  {
    id: "software-architecture",
    slug: "software-architecture",
    name: "Software Architecture",
    fullName: "Software Architecture & Design",
    categoryId: "engineering-practices",
    logo: "Layers",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 1990,
    description: "High-level structure of software systems.",
    whyWeUseIt: ["Scalable systems", "Maintainable code", "Clear structure"],
    bestFor: ["Large applications", "Long-term projects", "Enterprise systems"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["laravel", "nextjs", "microservices"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 94,
    color: "#475569",
  },
  {
    id: "production-debugging",
    slug: "production-debugging",
    name: "Production Debugging",
    fullName: "Production System Debugging",
    categoryId: "engineering-practices",
    logo: "Bug",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Debugging issues in live production environments.",
    whyWeUseIt: ["Fix issues safely", "Minimize downtime", "Find root causes"],
    bestFor: ["Production systems", "Critical applications", "High-availability apps"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["logging", "debugging", "monitoring"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 88,
    color: "#DC2626",
  },
  {
    id: "lifecycle-debugging",
    slug: "lifecycle-debugging",
    name: "Lifecycle Debugging",
    fullName: "Application Lifecycle Debugging",
    categoryId: "engineering-practices",
    logo: "RotateCw",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2010,
    description: "Debugging across the entire application lifecycle.",
    whyWeUseIt: ["Catch issues early", "Better QA", "Faster releases"],
    bestFor: ["All development", "Agile teams", "Quality-focused teams"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["testing", "debugging", "cicd"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#7C3AED",
  },
  {
    id: "performance-optimization-ep",
    slug: "performance-optimization-ep",
    name: "Performance Optimization",
    fullName: "Performance Optimization & Tuning",
    categoryId: "engineering-practices",
    logo: "Gauge",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2000,
    description: "Optimizing application performance at scale.",
    whyWeUseIt: ["Better user experience", "Lower costs", "Higher scalability"],
    bestFor: ["High-traffic apps", "Enterprise systems", "Performance-critical apps"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["redis", "postgresql", "devtools-performance-optimization"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 90,
    color: "#16A34A",
  },
  {
    id: "root-cause-analysis",
    slug: "root-cause-analysis",
    name: "Root Cause Analysis",
    fullName: "Root Cause Analysis Methodology",
    categoryId: "engineering-practices",
    logo: "Search",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 1990,
    description: "Process of identifying the root cause of problems.",
    whyWeUseIt: ["Prevent recurrence", "Improve systems", "Learn from incidents"],
    bestFor: ["Incident response", "System improvement", "Quality assurance"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["logging", "production-debugging", "testing"],
    experienceLevel: "Advanced",
    difficulty: "Advanced",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 87,
    color: "#6366F1",
  },
  {
    id: "testing-ep",
    slug: "testing-ep",
    name: "Testing",
    fullName: "Software Testing & Quality Assurance",
    categoryId: "engineering-practices",
    logo: "CheckCircle",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 1990,
    description: "Process of verifying that software meets requirements.",
    whyWeUseIt: ["Higher quality", "Fewer bugs", "Confident releases"],
    bestFor: ["All applications", "Critical systems", "Team collaboration"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["laravel", "nextjs", "cicd"],
    experienceLevel: "Core",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: true,
    status: "Stable",
    popularity: 95,
    color: "#22C55E",
  },
  {
    id: "deployment-verification",
    slug: "deployment-verification",
    name: "Deployment Verification",
    fullName: "Deployment Verification & Validation",
    categoryId: "engineering-practices",
    logo: "CheckCircle",
    iconType: "lucide",
    creator: "Industry Standard",
    releaseYear: 2010,
    description: "Verifying that deployments are successful and safe.",
    whyWeUseIt: ["Prevent bad deployments", "Quick rollbacks", "Confidence in releases"],
    bestFor: ["Production deployments", "Critical applications", "CI/CD pipelines"],
    officialWebsite: "",
    documentationUrl: "",
    githubUrl: "",
    relatedTechnologies: ["cicd", "testing", "github"],
    experienceLevel: "Advanced",
    difficulty: "Intermediate",
    usedInProjects: [],
    isCore: false,
    status: "Stable",
    popularity: 85,
    color: "#059669",
  },
];
